Repository DeFiCh/ain, pull requests merged in 2021-02, with the labels that each got.

#206 Make update token only need owner auth
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  test/functional/feature_poolpair_fork.py
  test/functional/test_runner.py
Labels: consensus

#214 Fix swap max price calculation
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  test/functional/feature_poolswap.py
Labels: consensus

#211 Reduce masternode collateral amount
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  src/miner.cpp
  src/pos.cpp
  src/pos_kernel.cpp
  src/pos_kernel.h
  src/test/blockencodings_tests.cpp
  src/test/blockfilter_index_tests.cpp
  src/test/double_sign.cpp
  src/test/miner_tests.cpp
  src/test/pos_tests.cpp
  test/functional/rpc_getcustomtx.py
  test/functional/rpc_mn_basic.py
Labels: consensus

#218 Anchor refactor
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/tx_check.cpp
  src/consensus/tx_check.h
  src/init.cpp
  src/logging.cpp
  src/logging.h
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/miner.cpp
  src/net_processing.cpp
  src/protocol.cpp
  src/protocol.h
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
  src/test/anchor_tests.cpp
  src/test/setup_common.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_anchor_rewards.py
  test/functional/feature_anchorauths.py
  test/functional/feature_anchorauths_pruning.py
  test/functional/feature_anchors.py
  test/functional/feature_communitybalance_reorg.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
Labels: consensus

#226 Pin github-actions to a full length commit SHA
  .github/workflows/dev-builds.yaml
  .github/workflows/prune-artifacts.yaml
  .github/workflows/release-builds.yaml
Labels: minor

#228 Adding variable for make args, ignore .vscode dir
  .gitignore
  make.sh
Labels: minor

#234 Refactor mn_rpc file and split into different categories based on RPC types
  src/Makefile.am
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/rpc_tokens.cpp
  src/rpc/register.h
  test/lint/check-rpc-mappings.py
  test/lint/lint-includes.sh
Labels: kind/refactor

#249 Move all anchors and validation to pending
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
Labels: kind/fix

#253 Reject paid confirmations. Only vote if not in IBD.
  src/masternodes/anchors.cpp
  src/net_processing.cpp
  src/validation.cpp
Labels: kind/fix

#229 Restore equal work handling on invalidate block
  src/validation.cpp
Labels: kind/fix

#247 Update setup-masternodes.md
  doc/setup-masternodes.md
Labels: kind/chore

#248 Hard code required SPV solution to related DeFi network
  src/init.cpp
  src/test/setup_common.cpp
  test/functional/feature_anchor_rewards.py
  test/functional/feature_anchorauths.py
  test/functional/feature_anchorauths_pruning.py
  test/functional/feature_anchors.py
  test/functional/feature_criminals.py
Labels: kind/fix
