Repository DeFiCh/ain, pull requests merged in 2021-04, with the labels that each got.

#300 Using enum instead of hardcoded number for tx destination
  src/chainparams.cpp
  src/init.cpp
  src/masternodes/anchors.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_masternodes.cpp
  src/rpc/util.cpp
  src/script/standard.h
  src/spv/spv_wrapper.cpp
  src/wallet/rpcwallet.cpp
Labels: kind/chore

#304 Adjust fork warning conditions
  src/validation.cpp
Labels: kind/fix

#302 Prevent accept bad hash block
  src/pos.cpp
  src/validation.cpp
Labels: kind/fix

#308 SPV Bitcoin HTLC
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/rpc/client.cpp
  src/script/standard.cpp
  src/script/standard.h
  src/spv/bitcoin/BRTransaction.cpp
  src/spv/bitcoin/BRTransaction.h
  src/spv/bitcoin/BRWallet.cpp
  src/spv/bitcoin/BRWallet.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
  src/spv/support/BRAddress.cpp
  src/spv/support/BRAddress.h
  src/wallet/rpcwallet.cpp
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  test/functional/data/spv_addresses.txt
  test/functional/feature_bitcoin_htlc.py
  test/functional/test_runner.py
Labels: kind/feature

#311 SPV HTLC Consistent key names and descriptions
  src/spv/spv_rpc.cpp
Labels: kind/chore

#307 Updated the getmintinginfo and getmininginfo to fix referencing on rval.
  src/rpc/mining.cpp
  src/validation.cpp
Labels: kind/fix

#310 SPV: Skip pending anchor until block confirmed
  src/masternodes/anchors.cpp
  src/spv/spv_wrapper.cpp
Labels: kind/fix

#312 Add SPV checkpoint to speed up resync
  src/spv/bitcoin/BRChainParams.cpp
  src/spv/bitcoin/BRChainParams.h
  src/spv/spv_wrapper.cpp
Labels: kind/chore

#319 Fix rpc parameter not converted in defi-cli
  src/rpc/client.cpp
Labels: kind/fix

#318 Update build and client versions
  share/genbuild.sh
  src/clientversion.cpp
Labels: kind/fix

#321 spv_listreceivedbyaddress
  src/rpc/client.cpp
  src/spv/bitcoin/BRWallet.cpp
  src/spv/bitcoin/BRWallet.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
Labels: kind/feature

#313 Feature/reorg to anchor height
  src/init.cpp
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/test/anchor_tests.cpp
  src/validation.cpp
Labels: kind/feature

#314 Randomise winning anchor on blockhash
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRWallet.cpp
  src/spv/bitcoin/BRWallet.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
  src/test/anchor_tests.cpp
  test/functional/feature_anchor_rewards.py
Labels: 1.7.x, kind/chore

#327 Skip blocks with higher than expected hash
  src/validation.cpp
Labels: kind/fix

#331 spv_validateaddress
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
Labels: kind/feature

#332 Split pool reward records
  src/masternodes/masternodes.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/rpc_accounts.cpp
  src/test/liquidity_tests.cpp
Labels: kind/fix

#330 Native CORS support for defichain
  src/httprpc.cpp
  src/httpserver.cpp
  src/httpserver.h
  src/init.cpp
  src/rpc/protocol.h
  test/functional/interface_http_cors.py
  test/functional/test_runner.py
Labels: kind/feature

#328 DFIP8 New emissions
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/communityaccounttypes.h
  src/masternodes/incentivefunding.h
  src/masternodes/rpc_accounts.cpp
  src/miner.cpp
  src/rpc/blockchain.cpp
  src/test/dip1fork_tests.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_dfip8_communitybalances.py
  test/functional/test_runner.py
Labels: kind/feature

#287 Oracle development
  configure.ac
  src/Makefile.am
  src/Makefile.test.include
  src/amount.h
  src/chainparams.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/oracles.cpp
  src/masternodes/oracles.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_oracles.cpp
  src/rpc/client.cpp
  src/rpc/register.h
  src/test/oracles_tests.cpp
  test/functional/feature_oracles.py
  test/functional/rpc_help.py
  test/functional/test_runner.py
  test/lint/check-rpc-mappings.py
  test/lint/lint-locale-dependence.sh
Labels: 1.7.x, kind/feature

#333 SPV show all addresses and add ismine
  src/spv/bitcoin/BRWallet.cpp
  src/spv/bitcoin/BRWallet.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
Labels: kind/feature

#334 Correct use of views in anchors
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
Labels: kind/bug

#325 SPV blocknotify/walletnotify
  src/init.cpp
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRPeerManager.h
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
Labels: kind/feature

#340 Feature/decodecustomtx
  src/masternodes/rpc_tokens.cpp
  src/rpc/client.cpp
  src/test/rpc_tests.cpp
  src/validation.cpp
Labels: kind/feature

#337 Extend block merkle root by hash of account changes
  src/hash.h
  src/masternodes/accountshistory.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/miner.cpp
  src/miner.h
  src/pos.cpp
  src/test/storage_tests.cpp
  src/validation.cpp
  test/functional/feature_accounts_validation.py
  test/functional/test_runner.py
Labels: kind/feature

#356 spv_getfeerate. SPV wallet fee filter for HTLC. SPV reset on reindex.
  src/init.cpp
  src/spv/bitcoin/BRWallet.cpp
  src/spv/bitcoin/BRWallet.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
Labels: kind/fix

#358 Add workflow_dispatch to github dev-build
  .github/workflows/dev-builds.yaml
Labels: kind/chore

#359 Specific error messages on SPV TX creation failure
  src/spv/bitcoin/BRWallet.cpp
  src/spv/bitcoin/BRWallet.h
  src/spv/spv_wrapper.cpp
Labels: kind/chore
