Repository DeFiCh/ain, pull requests merged in 2021-03, with the labels that each got.

#254 Wipe confs/revote after new team. New getactivemasternodes call.
  src/masternodes/anchors.cpp
  src/masternodes/rpc_masternodes.cpp
  src/rpc/client.cpp
  src/validation.cpp
Labels: kind/fix

#255 Flush when it's needed in reindex chainstate
  src/validation.cpp
Labels: kind/fix

#256 Wait wallet unlock to stake
  src/init.cpp
  src/miner.cpp
Labels: kind/fix

#259 Prevent race when multiple masternode operators are running
  src/miner.cpp
Labels: kind/fix

#258 Ensure masternode owner address is actually owned by the wallet
  src/masternodes/rpc_masternodes.cpp
  test/functional/rpc_mn_basic.py
Labels: kind/fix

#262 Update setup-masternodes.md
  doc/setup-masternodes.md
Labels: needs/kind

#263 Move anchor log to anchor debug log category
  src/masternodes/anchors.cpp
Labels: kind/docs

#261 Invalid tx should not be included in block
  src/miner.cpp
Labels: kind/fix

#264 Wipe mempool on restart or on failed block.
  src/miner.cpp
  src/validation.h
Labels: kind/fix

#266 tests: manually set persistmempool to true for tests that require it
  test/functional/mempool_persist.py
  test/functional/wallet_zapwallettxes.py
Labels: kind/fix

#268 Add newline to LogPrint messages
  src/masternodes/anchors.cpp
Labels: kind/fix

#267 Prefer entry time over hash in tx ordering
  src/miner.h
Labels: kind/fix

#265 Updated release process
  .github/workflows/release-builds.yaml
Labels: kind/chore

#272 Migrate Travis to Github workflows
  .github/workflows/dev-builds.yaml
  .github/workflows/lint.yaml
  .github/workflows/prune-artifacts.yaml
  .github/workflows/release-builds.yaml
  .github/workflows/tests.yaml
  ci/lint/04_install.sh
  ci/lint/05_before_script.sh
  ci/lint/06_script.sh
  ci/test/00_setup_env.sh
  ci/test/04_install.sh
Labels: kind/chore

#273 Remove Travis CI
  .travis.yml
Labels: kind/chore

#271 Log previous anchor in more anchor calls
  src/spv/spv_rpc.cpp
Labels: kind/feature

#274 update status badge to gha as travis is removed
  README.md
Labels: kind/docs

#275 Check pending anchors in same ordrer as top anchor selection
  src/masternodes/anchors.cpp
Labels: kind/fix

#277 Test and compare anchor and pending anchor selection logic
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/test/anchor_tests.cpp
Labels: kind/chore

#269 Remove dead code
  src/validation.cpp
Labels: kind/chore

#250 Enable cxx warnings per default
  configure.ac
  src/masternodes/incentivefunding.cpp
  src/masternodes/masternodes.h
  src/masternodes/poolpairs.h
  src/masternodes/tokens.cpp
  src/pos.cpp
  src/spv/bitcoin/BRPeer.cpp
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/streams.h
  src/test/applytx_tests.cpp
  src/test/blockfilter_index_tests.cpp
  src/test/denialofservice_tests.cpp
  src/test/double_sign.cpp
  src/test/liquidity_tests.cpp
  src/test/miner_tests.cpp
  src/test/pos_tests.cpp
  src/test/txvalidationcache_tests.cpp
  src/test/util_tests.cpp
  src/txdb.cpp
  src/undo.h
  src/validation.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
Labels: kind/fix

#244 Migrate to new network message
  src/net.cpp
  src/net_processing.cpp
Labels: kind/fix

#276 Fix oracle rpc api bugs
  src/masternodes/oracles.h
  src/masternodes/rpc_oracles.cpp
  src/rpc/client.cpp
  test/functional/test_runner.py
Labels: kind/chore

#284 Scale difficulty target and limit future block time
  src/chain.h
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/pos.cpp
  src/pos_kernel.cpp
  src/pos_kernel.h
  src/rpc/blockchain.cpp
  src/test/blockencodings_tests.cpp
  src/test/double_sign.cpp
  src/test/pos_tests.cpp
  src/validation.cpp
  test/functional/rpc_blockchain.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/fix

#289 Coinage count from MN creation or fork height
  src/chainparams.cpp
  src/consensus/tx_verify.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_tokens.cpp
  src/miner.cpp
  src/pos_kernel.cpp
  src/test/applytx_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
Labels: kind/feature

#290 Always calculate coinage, do not toggle on minted blocks
  src/pos_kernel.cpp
Labels: kind/fix

#282 Bitcoin support via SPV
  src/init.cpp
  src/logging.cpp
  src/logging.h
  src/rpc/client.cpp
  src/spv/bitcoin/BRChainParams.cpp
  src/spv/bitcoin/BRChainParams.h
  src/spv/bitcoin/BRPeer.cpp
  src/spv/bitcoin/BRPeer.h
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRPeerManager.h
  src/spv/bitcoin/BRTransaction.h
  src/spv/bitcoin/BRWallet.cpp
  src/spv/bitcoin/BRWallet.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
  src/spv/support/BRLargeInt.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.h
  test/functional/feature_bitcoin_wallet.py
  test/functional/p2p_compactblocks.py
  test/functional/p2p_disconnect_ban.py
  test/functional/p2p_invalid_block.py
  test/functional/p2p_invalid_locator.py
  test/functional/p2p_invalid_tx.py
  test/functional/p2p_node_network_limited.py
  test/functional/test_framework/messages.py
  test/functional/test_framework/mininode.py
  test/functional/test_framework/test_node.py
  test/functional/test_runner.py
  test/lint/lint-python-dead-code-whitelist
Labels: kind/feature

#280 upgraded oss-governance-bot to v2
  .github/CODEOWNERS
  .github/governance.yml
  .github/workflows/oss-governance-bot.yml
Labels: kind/chore

#288 Updated node errors to return the error string with decimal places.
  src/amount.h
  src/test/amount_tests.cpp
  src/test/applytx_tests.cpp
  test/functional/feature_poolpair_liquidity.py
Labels: kind/fix

#293 Updated listmasternodes default pagination count to 1000000
  src/masternodes/rpc_masternodes.cpp
Labels: kind/fix

#295 Speedup getmasternodeblocks
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/rpc_masternodes.cpp
Labels: kind/fix

#294 Limit db writes in normal node operation
  src/init.cpp
  src/validation.cpp
  src/validation.h
Labels: kind/fix

#296 Show block reward in listaccounthistory
  src/masternodes/rpc_accounts.cpp
  test/functional/rpc_listaccounthistory.py
Labels: kind/feature

#297 Feature/getmininginfo
  src/miner.cpp
  src/miner.h
  src/rpc/mining.cpp
  test/functional/rpc_getmininginfo.py
  test/functional/test_runner.py
Labels: kind/feature
