Repository DeFiCh/ain, pull requests merged in 2021-09, with the labels that each got.

#698 Auction bid rpc and consensus implementation
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_vault.cpp
  src/masternodes/vault.cpp
  src/masternodes/vault.h
  src/rpc/client.cpp
  src/validation.cpp
Labels: kind/feature

#700 Take loan feature
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_icxorderbook.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  src/rpc/client.cpp
  test/functional/feature_loan_takeloan.py
  test/functional/test_runner.py
Labels: consensus, kind/feature, area/loan

#705 - Fix error msg on updateLoanToken
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#704 Fix getmasternodeblocks
  src/masternodes/rpc_masternodes.cpp
  test/functional/rpc_mn_basic.py
Labels: kind/fix

#696 Add post EP workaround to force one subnode0 stake before subnode1
  src/miner.cpp
Labels: kind/fix

#708 Update minor version
  configure.ac
Labels: kind/chore

#715 getvault add USD loan/collateral value
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan_vault.py
Labels: kind/fix

#712 Keep track of vault interest contribution
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/test/loan_tests.cpp
  src/validation.cpp
Labels: kind/feature

#716 Feature/listauctions
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan_vault.py
Labels: kind/feature

#713 Fix without default loan schema node crash
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
Labels: kind/fix

#720 Fix updateloantoken mintable has problem
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#717 Fix getmasternodeblocks to retrieve all blocks from all subnodes
  src/masternodes/rpc_masternodes.cpp
Labels: kind/fix

#725 Don't check IBD for getvault
  src/masternodes/rpc_vault.cpp
Labels: kind/fix

#730 Make dummy data specific to TX
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#729 v1.8.4
  configure.ac
Labels: kind/chore

#723 Fix/auctionbid rpc
  src/masternodes/rpc_vault.cpp
  src/masternodes/vault.cpp
  src/masternodes/vault.h
  src/validation.cpp
  test/functional/feature_loan.py
  test/functional/test_runner.py
Labels: kind/fix

#732 getvault show interest + #731 fix
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan_vault.py
Labels: kind/fix

#734 Refactor rpc test execution
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_icxorderbook.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/rpc_vault.cpp
Labels: kind/chore

#733 Refactor code in connectblock to seperate functions
  src/validation.cpp
  src/validation.h
Labels: kind/refactor

#740 Refactor vault implementation
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  src/masternodes/vault.cpp
  src/masternodes/vault.h
  src/test/loan_tests.cpp
  src/validation.cpp
  test/functional/feature_loan_takeloan.py
  test/functional/feature_loan_vault.py
Labels: kind/chore

#743 Fix/full loan vault tests
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan.py
  test/functional/feature_loan_vault.py
  test/functional/test_runner.py
Labels: kind/fix

#744 Interest calculation as percentage
  src/masternodes/loan.cpp
  src/test/loan_tests.cpp
  test/functional/feature_loan_takeloan.py
  test/functional/feature_loan_vault.py
Labels: kind/fix

#745 Payback and auction fees
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_accounts.cpp
  src/validation.cpp
  test/functional/feature_loan_takeloan.py
Labels: kind/feature

#742 Aggregate oracle price
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_vault.cpp
  src/test/loan_tests.cpp
  src/validation.cpp
  test/functional/feature_loan.py
  test/functional/feature_loan_setcollateraltoken.py
  test/functional/feature_loan_setloantoken.py
  test/functional/feature_loan_takeloan.py
  test/functional/feature_loan_vault.py
Labels: consensus, wip, kind/fix, area/loan

#748 Add revert handlers to icx / loans
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#756 Continue fixing edge case
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/validation.cpp
  test/functional/feature_loan_takeloan.py
Labels: kind/fix

#757 Add optional destination address to takeloan
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
Labels: kind/feature

#758 Revert subAmount. Update test
  src/masternodes/mn_checks.cpp
  test/functional/feature_loan_takeloan.py
Labels: kind/fix

#764 Including tx fee into block rewards
  src/miner.cpp
  test/functional/feature_block_reward.py
  test/functional/test_runner.py
Labels: kind/fix

#763 Adds pagination and filter options to listvaults RPC
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_vault.cpp
  src/masternodes/vault.cpp
  src/masternodes/vault.h
  src/rpc/client.cpp
  test/functional/feature_loan_vault.py
Labels: kind/feature
