Repository DeFiCh/ain, pull requests merged in 2021-07, with the labels that each got.

#571 Fix status in icx_getorder rpc
  src/masternodes/icxorder.cpp
  src/masternodes/icxorder.h
  src/masternodes/rpc_icxorderbook.cpp
  test/functional/feature_icx_orderbook.py
Labels: kind/fix

#568 Feature/pagination lists rpc
  src/masternodes/rpc_oracles.cpp
  src/rpc/client.cpp
Labels: kind/feature

#574 Specify oracle weight age between 0 and 255
  src/masternodes/rpc_oracles.cpp
Labels: kind/fix

#473 Loan setcollateraltoken
  src/Makefile.am
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/rpc/client.cpp
  src/rpc/register.h
  test/functional/feature_loan_setcollateraltoken.py
  test/functional/rpc_help.py
  test/functional/test_runner.py
  test/lint/check-rpc-mappings.py
Labels: area/loan, kind/feature

#578 Test foundation balance survives reorg
  test/functional/feature_community_development_funds.py
Labels: kind/chore

#579 Feature/getmintinginfo to getmininginfo
  src/rpc/mining.cpp
  test/functional/rpc_getmininginfo.py
Labels: kind/feature

#559 Send from UTXOs, do not subtract fee from amount
  src/masternodes/rpc_accounts.cpp
  test/functional/feature_sendutxosfrom.py
Labels: kind/fix

#469 Introduce pool reward type
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/rpc_accounts.cpp
  src/test/liquidity_tests.cpp
Labels: kind/feature

#562 Feature onchain timelock
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/pos.cpp
  src/pos_kernel.cpp
  src/pos_kernel.h
  src/rpc/mining.cpp
  src/test/blockencodings_tests.cpp
  src/test/mn_blocktime_tests.cpp
  src/test/pos_tests.cpp
  test/functional/feature_burn_address.py
  test/functional/feature_longterm_lockin.py
  test/functional/test_runner.py
Labels: kind/feature

#587 Fix/setoracledata timestamp validation
  src/masternodes/rpc_oracles.cpp
  test/functional/feature_oracles.py
Labels: kind/fix

#582 Loan scheme
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/rpc/client.cpp
  test/functional/feature_loan_scheme.py
  test/functional/rpc_getcustomtx.py
  test/functional/test_runner.py
Labels: kind/feature

#557 Apply token filter to rewards in history
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#518 Prevent resign during PRE_ENABLED state
  src/masternodes/masternodes.cpp
  test/functional/rpc_mn_basic.py
Labels: consensus, kind/fix

#586 Reduce future block time to 30 seconds
  src/chain.h
  src/miner.cpp
  src/miner.h
  src/validation.cpp
Labels: kind/fix

#592 Check for and reject entries with duplicates
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/masternodes/mn_checks.cpp
  src/test/anchor_tests.cpp
Labels: kind/fix

#598 Hold confirms on BTC TX height, hash and signed CKeyID
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
Labels: kind/chore

#601 Add hard coded seed for devnet
  src/chainparams.cpp
  src/chainparamsseeds.h
Labels: kind/feature

#541 [On-Chain-Government] Community Fund Request proposal
  src/Makefile.am
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/proposals.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_proposals.cpp
  src/rpc/client.cpp
  src/rpc/register.h
  src/validation.cpp
  test/functional/feature_on_chain_government.py
  test/functional/rpc_help.py
  test/functional/test_runner.py
  test/lint/check-rpc-mappings.py
Labels: area/governance, kind/feature

#596 [On-Chain-Government] Vote of Confidence
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/proposals.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_proposals.cpp
  src/rpc/client.cpp
  test/functional/feature_on_chain_government.py
Labels: area/governance, kind/feature

#605 Complete foundation auth removal
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_proposals.cpp
Labels: area/governance, consensus, kind/fix

#604 Set Eunos and Paya forks on devnet
  src/chainparams.cpp
Labels: kind/chore

#599 ICX hardfork fixes
  src/masternodes/icxorder.cpp
  src/masternodes/icxorder.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_icxorderbook.cpp
  src/validation.cpp
  test/functional/feature_icx_orderbook.py
  test/functional/feature_icx_orderbook_errors.py
Labels: area/interchain-exchange, consensus, kind/fix

#611 Change the minimum timeout for HTLCs to ~12h period.
  src/masternodes/icxorder.cpp
  src/masternodes/icxorder.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_icxorderbook.cpp
  test/functional/feature_icx_orderbook.py
  test/functional/feature_icx_orderbook_errors.py
Labels: area/interchain-exchange, consensus, kind/fix

#607 Timelock expiration
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/pos.cpp
  src/rpc/mining.cpp
  test/functional/feature_longterm_lockin.py
Labels: kind/feature

#613 Set version to 1.8.0
  configure.ac
Labels: kind/chore

#597 Don't allow blockchain reverting prior last checkpoint in any case
  src/validation.cpp
Labels: kind/fix

#614 Set testnet EP fork and increment PROTOCOL_VERSION.
  src/chainparams.cpp
  src/version.h
Labels: kind/chore

#530 v1.8.0
  configure.ac
  src/chain.h
  src/chainparams.cpp
  src/chainparamsseeds.h
  src/consensus/params.h
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/masternodes/icxorder.cpp
  src/masternodes/icxorder.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_icxorderbook.cpp
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/miner.h
  src/pos.cpp
  src/pos_kernel.cpp
  src/pos_kernel.h
  src/rpc/mining.cpp
  src/test/anchor_tests.cpp
  src/test/blockencodings_tests.cpp
  src/test/mn_blocktime_tests.cpp
  src/test/pos_tests.cpp
  src/validation.cpp
  src/version.h
  test/functional/feature_burn_address.py
  test/functional/feature_icx_orderbook.py
  test/functional/feature_icx_orderbook_errors.py
  test/functional/feature_longterm_lockin.py
  test/functional/rpc_mn_basic.py
  test/functional/test_runner.py
Labels: kind/feature, release-staging, wip

#615 Add timelock to metadata check post-EP
  src/masternodes/rpc_masternodes.cpp
Labels: kind/fix

#616 Set mainnet EunosPaya height
  src/chainparams.cpp
Labels: kind/chore

#624 Increment EunosPaya fork height
  src/chainparams.cpp
Labels: kind/chore

#622 Update seeds
  contrib/seeds/generate-seeds.py
  contrib/seeds/nodes_devnet.txt
  contrib/seeds/nodes_main.txt
  contrib/seeds/nodes_test.txt
  src/chainparamsseeds.h
Labels: kind/chore

#631 Fix intermittent DIP1 test failure by allowing time to reindex
  test/functional/feature_dip1.py
Labels: kind/fix

#632 Remove EunosSims
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/masternodes.cpp
Labels: kind/chore

#630 Fix intermittent poolswap test failure by wiping mempool after chain revert
  test/functional/feature_poolswap_mechanism.py
Labels: kind/fix

#633 Refactor POS check method signatures and arg validations
  src/bench/checkblock.cpp
  src/bench/duplicate_inputs.cpp
  src/blockencodings.cpp
  src/chainparams.cpp
  src/miner.cpp
  src/pos.cpp
  src/pos.h
  src/pos_kernel.cpp
  src/pos_kernel.h
  src/test/blockencodings_tests.cpp
  src/test/pos_tests.cpp
  src/validation.cpp
  src/validation.h
Labels: kind/refactor

#634 Format some code and fix lint error
  src/pos_kernel.cpp
  test/lint/lint-circular-dependencies.sh
  test/lint/lint-includes.sh
Labels: kind/fix

#638 Fix info messages
  src/masternodes/rpc_proposals.cpp
Labels: kind/fix

#637 Keep last undo prune height
  src/validation.cpp
Labels: kind/fix

#639 Fix delay for masternode activation/resign delay
  src/masternodes/masternodes.cpp
Labels: consensus, kind/fix

#628 Add support for subnode staking
  src/Makefile.test.include
  src/bench/checkblock.cpp
  src/bench/duplicate_inputs.cpp
  src/blockencodings.cpp
  src/chainparams.cpp
  src/init.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/pos.cpp
  src/pos.h
  src/pos_kernel.cpp
  src/pos_kernel.h
  src/rpc/mining.cpp
  src/test/blockencodings_tests.cpp
  src/test/blockfilter_index_tests.cpp
  src/test/miner_tests.cpp
  src/test/mn_blocktime_tests.cpp
  src/test/pos_tests.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_icx_orderbook.py
  test/functional/feature_icx_orderbook_errors.py
  test/functional/feature_longterm_lockin.py
  test/functional/rpc_mn_basic.py
  test/lint/lint-circular-dependencies.sh
  test/lint/lint-includes.sh
Labels: kind/feature

#643 Update mempool reorg on high hash error
  src/validation.cpp
Labels: kind/fix

#641 Eunos Paya revised height
  src/chainparams.cpp
Labels: kind/chore

#640 Add Vault struct and `createvault` & `listvaults` rpc commads
  .github/workflows/tests.yaml
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/rpc/client.cpp
  src/rpc/register.h
  test/functional/feature_loan_scheme.py
Labels: kind/feature

#618 Cap regtest blocktime to median time + 1 to avoid errors
  src/miner.cpp
  test/functional/feature_masternode_operator.py
Labels: kind/fix

#617 Add update, default and destroy loan scheme calls
  .github/workflows/tests.yaml
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/rpc/client.cpp
  src/rpc/register.h
  src/validation.cpp
  test/functional/feature_loan_scheme.py
  test/functional/rpc_getcustomtx.py
Labels: kind/feature
