Repository DeFiCh/ain, pull requests merged in 2021-08, with the labels that each got.

#653 Move CheckPendingAnchors out of cs_main lock
  src/validation.cpp
Labels: kind/fix

#651 Fix spv help message typo
  src/spv/spv_rpc.cpp
Labels: kind/fix

#649 Fix random unit test fail
  test/functional/feature_icx_orderbook.py
Labels: kind/fix

#658 Enable parallel make for builds
  make.sh
Labels: kind/chore

#657 v1.8.1
  configure.ac
Labels: kind/chore

#659 Enable parallel builds on docker containers
  contrib/dockerfiles/arm-linux-gnueabihf.dockerfile
  contrib/dockerfiles/x86_64-apple-darwin11.dockerfile
  contrib/dockerfiles/x86_64-pc-linux-gnu.dockerfile
  contrib/dockerfiles/x86_64-w64-mingw32.dockerfile
Labels: kind/chore

#660 Add getvault + change id to Vault struct
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  test/functional/feature_loan_scheme.py
Labels: kind/feature

#646 Updated the code to generate blocks for the given address.
  src/key_io.cpp
  src/key_io.h
  src/rpc/mining.cpp
  test/functional/rpc_getmininginfo.py
Labels: kind/fix

#663 Fix ICX rpc descriptions
  src/masternodes/rpc_icxorderbook.cpp
Labels: kind/fix, area/interchain-exchange

#661 Init dev of setloantoken
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/tokens.h
  src/rpc/client.cpp
  test/functional/feature_loan_setloantoken.py
  test/functional/test_runner.py
Labels: kind/feature, area/loan

#662 Fix to remove collateral token when factor set to 0
  src/masternodes/rpc_loan.cpp
  test/functional/feature_loan_setcollateraltoken.py
Labels: kind/fix, area/loan

#664 Enable lint in epic/*
  .github/workflows/lint.yaml
Labels: kind/fix

#665 Loan token interest calculation
  src/Makefile.test.include
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/test/loan_tests.cpp
Labels: kind/feature

#672 Update previous checkpoint height
  src/validation.cpp
Labels: kind/fix

#675 updatevault rpc + validation + tests
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/rpc/client.cpp
  src/validation.cpp
  test/functional/feature_loan_scheme.py
Labels: kind/feature

#677 Only check previous anchor when SPV enabled
  src/masternodes/anchors.cpp
Labels: kind/fix

#674 Fix multiple pool rewards history
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#673 Collateralization ratio calculation
  src/consensus/params.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/oracles.cpp
  src/masternodes/oracles.h
  src/test/loan_tests.cpp
  src/test/oracles_tests.cpp
  src/validation.cpp
Labels: kind/feature

#678 Discard accounts changes on clearing mempool
  src/txmempool.cpp
Labels: kind/fix

#680 Validate loan scheme on create/update vault.
  src/masternodes/mn_checks.cpp
  test/functional/feature_loan_scheme.py
Labels: kind/fix

#682 Split loan / vault implementation
  src/Makefile.am
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.h
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  src/masternodes/vault.cpp
  src/masternodes/vault.h
Labels: kind/refactor

#683 Validate on createvault
  src/masternodes/mn_checks.cpp
  test/functional/feature_loan_scheme.py
Labels: kind/fix

#681 Update version
  configure.ac
Labels: kind/chore

#685 Add EunosPaya height to blockchaininfo
  src/rpc/blockchain.cpp
  test/functional/rpc_blockchain.py
Labels: kind/fix

#676 Feature composite swap
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/poolpairs.h
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/tokens.h
  src/rpc/blockchain.cpp
  test/functional/feature_poolswap.py
  test/functional/feature_poolswap_composite.py
  test/functional/test_runner.py
Labels: kind/feature

#688 Trigger auction, split auction into batches, initial auction bid data
  src/amount.h
  src/consensus/params.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/vault.cpp
  src/masternodes/vault.h
  src/test/loan_tests.cpp
  src/validation.cpp
Labels: kind/feature

#702 Compile time db indices validation
  src/flushablestorage.h
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/gv.cpp
  src/masternodes/gv.h
  src/masternodes/icxorder.cpp
  src/masternodes/icxorder.h
  src/masternodes/incentivefunding.cpp
  src/masternodes/incentivefunding.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/oracles.cpp
  src/masternodes/oracles.h
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/masternodes/undos.cpp
  src/masternodes/undos.h
  src/masternodes/vault.cpp
  src/masternodes/vault.h
  src/test/storage_tests.cpp
Labels: kind/feature

#703 Fix minor loan typos and format
  src/masternodes/loan.cpp
  src/masternodes/rpc_loan.cpp
Labels: kind/fix
