Repository DeFiCh/ain, pull requests merged in 2021-05, with the labels that each got.

#363 Add docker build to dev builds
  .github/workflows/dev-builds.yaml
Labels: area/workflow, kind/chore

#364 HTLC set min timeout
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/spv/spv_rpc.cpp
  test/functional/feature_bitcoin_htlc.py
Labels: kind/chore

#355 Ensure auto auth not overlap regular tx inputs or vice versa
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  test/functional/feature_lock_unspends.py
  test/functional/test_runner.py
Labels: kind/fix

#354 Track UTXO and tokens sent to burn address
  configure.ac
  contrib/testgen/gen_burn_addr.py
  depends/Makefile
  depends/README.md
  depends/config.site.in
  depends/packages/boost.mk
  depends/packages/expat.mk
  depends/packages/fontconfig.mk
  depends/packages/freetype.mk
  depends/packages/libXau.mk
  depends/packages/libxcb.mk
  depends/packages/native_protobuf.mk
  depends/packages/packages.mk
  depends/packages/protobuf.mk
  depends/packages/qrencode.mk
  depends/packages/qt.mk
  depends/packages/xcb_proto.mk
  depends/packages/xproto.mk
  depends/packages/zlib.mk
  depends/patches/qt/fix_configure_mac.patch
  depends/patches/qt/fix_no_printer.patch
  depends/patches/qt/fix_qt_pkgconfig.patch
  depends/patches/qt/fix_rcc_determinism.patch
  depends/patches/qt/fix_riscv64_arch.patch
  depends/patches/qt/mac-qmake.conf
  depends/patches/qt/no-xlib.patch
  depends/patches/qt/xkb-default.patch
  src/Makefile.am
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_accounts.cpp
  src/rpc/client.cpp
  src/txmempool.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_burn_address.py
  test/functional/feature_eunos_balances.py
  test/functional/test_framework/test_framework.py
  test/functional/test_runner.py
Labels: kind/feature

#378 New difficulty adjust period
  src/bench/duplicate_inputs.cpp
  src/chainparams.cpp
  src/consensus/params.h
  src/miner.cpp
  src/pos.cpp
  src/pos.h
  src/validation.cpp
Labels: kind/feature

#382 net: Add a community-operated DNS seed for defichain mainnet nodes
  src/chainparams.cpp
Labels: kind/feature

#384 Remove Qt from depends on master
  configure.ac
  depends/Makefile
  depends/README.md
  depends/config.site.in
  depends/packages/boost.mk
  depends/packages/expat.mk
  depends/packages/fontconfig.mk
  depends/packages/freetype.mk
  depends/packages/libXau.mk
  depends/packages/libxcb.mk
  depends/packages/native_protobuf.mk
  depends/packages/packages.mk
  depends/packages/protobuf.mk
  depends/packages/qrencode.mk
  depends/packages/qt.mk
  depends/packages/xcb_proto.mk
  depends/packages/xproto.mk
  depends/packages/zlib.mk
  depends/patches/qt/fix_configure_mac.patch
  depends/patches/qt/fix_no_printer.patch
  depends/patches/qt/fix_qt_pkgconfig.patch
  depends/patches/qt/fix_rcc_determinism.patch
  depends/patches/qt/fix_riscv64_arch.patch
  depends/patches/qt/mac-qmake.conf
  depends/patches/qt/no-xlib.patch
  depends/patches/qt/xkb-default.patch
  src/Makefile.am
Labels: kind/chore

#389 Update CODEOWNERS to individuals instead of team
  .github/CODEOWNERS
Labels: kind/chore

#390 Change daily LP rewards automatically on subsidy reduction
  src/init.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/validation.cpp
  test/functional/feature_burn_address.py
  test/functional/feature_dfip8_communitybalances.py
  test/functional/feature_poolswap_mechanism.py
  test/functional/feature_setgov.py
Labels: kind/feature

#335 ICX Orderbook
  .gitignore
  src/Makefile.am
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/icx_takerfee_per_btc.h
  src/masternodes/gv.cpp
  src/masternodes/icxorder.cpp
  src/masternodes/icxorder.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_icxorderbook.cpp
  src/rpc/client.cpp
  src/rpc/register.h
  src/validation.cpp
  test/functional/feature_burn_address.py
  test/functional/feature_icx_orderbook.py
  test/functional/feature_icx_orderbook_errors.py
  test/functional/rpc_help.py
  test/functional/test_runner.py
  test/lint/check-rpc-mappings.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/feature

#391 Updated Eunos upgrade heights for mainnet and testnet
  src/chainparams.cpp
Labels: area/consensus

#395 Set Ubuntu 18.04 as minimum for tests and builds.
  .github/workflows/dev-builds.yaml
  .github/workflows/lint.yaml
  .github/workflows/release-builds.yaml
  .github/workflows/tests.yaml
Labels: kind/chore

#408 Fix/prevent reverts
  src/consensus/validation.h
  src/validation.cpp
Labels: kind/fix

#414 Add checkpoint to testnet
  src/chainparams.cpp
Labels: kind/chore

#416 Fix calculating owner rewards and returning takerFee on close offer.
  src/masternodes/icxorder.cpp
  src/masternodes/mn_checks.cpp
  src/validation.cpp
  test/functional/feature_icx_orderbook.py
Labels: kind/fix

#419 Increase masternode registration and resign delay
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/rpc_masternodes.cpp
  test/functional/rpc_mn_basic.py
Labels: kind/chore, needs/kind

#424 SPV add call, fix Windows connection issue and set Eunos height.
  src/chainparams.cpp
  src/logging.cpp
  src/logging.h
  src/spv/bitcoin/BRPeer.cpp
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRPeerManager.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
Labels: kind/chore

#426 Increment PROTOCOL_VERSION
  src/version.h
  test/functional/test_framework/messages.py
Labels: kind/chore

#417 updated oss governance workflow
  .github/workflows/oss-governance-bot.yml
  .github/workflows/oss-governance-project-issue.yml
  .github/workflows/oss-governance-project-pr.yml
  .github/workflows/sync-labels.yml
Labels: kind/chore

#432 Add RPC call sendutxosfrom
  src/masternodes/rpc_accounts.cpp
  src/rpc/client.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/rpcwallet.h
  test/functional/feature_sendutxosfrom.py
  test/functional/test_runner.py
Labels: kind/feature

#385 Remove OpenSSL and Qt remnants
  configure.ac
  depends/packages/openssl.mk
  depends/packages/packages.mk
  share/qt/Info.plist.in
  share/qt/extract_strings_qt.py
  src/Makefile.am
  src/Makefile.bench.include
  src/Makefile.test.include
  src/compat/byteswap.h
  src/init.cpp
  src/random.cpp
  src/random.h
Labels: kind/dependencies

#377 Don't stake in disconnecting process
  src/miner.cpp
  src/validation.cpp
  src/validation.h
Labels: kind/feature

#436 Fix to always return array for "amounts" in listaccounthistory
  src/masternodes/rpc_accounts.cpp
  test/functional/rpc_listaccounthistory.py
Labels: kind/fix

#429 Revert account balance in listaccounthistory pagination
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#434 Load minter last times into memory cache
  src/init.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/rpc_masternodes.cpp
  src/pos_kernel.cpp
Labels: kind/feature

#438 Add new checkpoint to minimize undo data
  src/chainparams.cpp
Labels: kind/chore

#444 Removed minter cache
  src/masternodes/masternodes.cpp
Labels: needs/kind

#445 Restore minter cache
  src/pos_kernel.cpp
Labels: needs/kind

#449 Notice in log that pruning undo can take a while
  src/validation.cpp
Labels: kind/fix

#452 Remove minter cache
  src/init.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/pos_kernel.cpp
Labels: kind/bug

#457 Add sleep after failed validation
  src/validation.cpp
Labels: kind/fix

#453 Ensure connect block is flushed its data
  src/pos_kernel.cpp
Labels: kind/fix

#450 Fix/getmininginfo lastblockcreationattempt multiple mns
  src/miner.cpp
  test/functional/rpc_getmininginfo.py
Labels: kind/fix

#371 Defer chain lock to caller to allow atomic lock
  src/interfaces/chain.cpp
  src/interfaces/chain.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_oracles.cpp
  src/rpc/rawtransaction.cpp
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/sync.h
  src/test/sync_tests.cpp
  src/validation.cpp
  src/wallet/feebumper.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
Labels: kind/fix
