Repository DeFiCh/ain, pull requests merged in 2021-06, with the labels that each got.

#468 Set daily reward as daily and not per block
  src/validation.cpp
  test/functional/feature_poolswap_mechanism.py
  test/functional/feature_setgov.py
Labels: kind/fix

#481 Remove anchor reward
  src/miner.cpp
Labels: kind/chore

#483 Revert invalid chain
  src/validation.cpp
Labels: kind/fix

#465 Add ismine to getmasternode and listmasternodes
  src/masternodes/rpc_masternodes.cpp
Labels: kind/chore

#485 fix typo `ownerIsMine`
  src/masternodes/rpc_masternodes.cpp
Labels: kind/fix

#488 Only skip anchor TX on mainnet
  src/miner.cpp
Labels: kind/fix

#482 Hardfork to disable account merkle root check
  src/chainparams.cpp
  src/consensus/params.h
  src/miner.cpp
  src/validation.cpp
Labels: kind/fix

#490 Prevent block invalidation prior last checkpoint
  src/validation.cpp
Labels: kind/fix

#489 Revert invalid chain if we partial connect its blocks
  src/validation.cpp
Labels: kind/fix

#491 Enable anchor payout on hard fork
  src/miner.cpp
Labels: kind/feature

#493 Fix the loop when block with high-hash comes
  src/validation.cpp
Labels: kind/fix

#494 Do not mark fInvalidFound true on high-hash block
  src/validation.cpp
Labels: kind/fix

#476 Better handle skipped txs
  src/Makefile.am
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_tokens.cpp
  src/masternodes/skipped_txs.cpp
Labels: kind/fix

#478 Correct display latest account history
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#477 Only change daily reward when subsidy differs
  src/validation.cpp
Labels: kind/chore

#472 Using clang 11 to compile on linux and MacOS
  contrib/dockerfiles/x86_64-pc-linux-gnu.dockerfile
  make.sh
Labels: kind/feature

#471 Check error msg after catch. Provide failing buyer pubkey case.
  test/functional/feature_bitcoin_htlc.py
Labels: kind/fix

#369 Do not allow checkpoint height to be reverted
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/validation.cpp
  test/functional/feature_checkpoint.py
  test/functional/test_runner.py
Labels: kind/fix

#486 Surangap/regtest chainparams jellyfish
  src/chainparams.cpp
  src/init.cpp
  test/functional/feature_jellyfish_initial_funds.py
  test/functional/test_runner.py
Labels: kind/chore

#496 Add jellyfish tests to CI
  .github/workflows/jellyfish-tests.yml
Labels: kind/chore

#455 Re-enable Python test
  test/functional/feature_block.py
Labels: kind/fix

#487 Change staking to single threaded and precompute merkle root
  src/init.cpp
  src/miner.cpp
  src/miner.h
  src/rpc/mining.cpp
Labels: kind/feature

#506 Set all Eunos height to be the same
  src/chainparams.cpp
Labels: kind/bug

#508 Remove lock from CheckKernelHash
  src/pos_kernel.cpp
Labels: kind/chore

#502 Allow coin override while minter packages txs
  src/miner.cpp
Labels: kind/fix

#495 Combine incentive fund into burn. Show emission burn on burn info.
  src/masternodes/rpc_accounts.cpp
  src/rpc/blockchain.cpp
  test/functional/feature_communitybalance_reorg.py
  test/functional/feature_dfip8_communitybalances.py
  test/functional/feature_dip1.py
Labels: kind/chore

#509 Rollback testnet further
  src/chainparams.cpp
Labels: kind/fix

#503 Break out of high-hash loop
  src/validation.cpp
Labels: kind/fix

#475 Update version tag to 1.7.5
  configure.ac
Labels: kind/fix

#515 v1.7.9
  configure.ac
Labels: kind/chore

#511 Keep mempool accounts view cache
  src/flushablestorage.h
  src/test/storage_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
Labels: kind/feature

#516 Fix passing inputs for ICX RPCs
  src/chainparams.cpp
  src/masternodes/rpc_icxorderbook.cpp
  src/rpc/client.cpp
Labels: kind/fix

#517 Do not keep failed tx coins in miner cache
  src/miner.cpp
Labels: kind/fix

#499 Limit max tip age to reasonable value
  src/validation.h
Labels: kind/fix

#498 Fix accounts performance issue
  src/bloom.cpp
  src/hash.cpp
  src/hash.h
  src/masternodes/poolpairs.cpp
  src/masternodes/rpc_accounts.cpp
  src/test/hash_tests.cpp
  src/wallet/ismine.cpp
Labels: kind/fix

#467 Faster calculation of anchoring teams
  src/masternodes/anchors.cpp
  src/masternodes/masternodes.cpp
  src/test/mn_blocktime_tests.cpp
Labels: kind/chore

#466 Fix if else using same condition
  src/masternodes/rpc_customtx.cpp
Labels: kind/fix

#519 Remove unneeded declarations
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRPeerManager.h
Labels: kind/chore

#520 Added continue on error to jellyfish test
  .github/workflows/jellyfish-tests.yml
Labels: kind/chore

#514 Increase time range for staking
  src/miner.cpp
  src/miner.h
  src/validation.cpp
  test/functional/p2p_unrequested_blocks.py
Labels: kind/feature

#505 Solve pos puzzle before create and propagate a block
  src/bench/duplicate_inputs.cpp
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/miner.h
  src/pos.cpp
  src/pos.h
  src/pos_kernel.cpp
  src/pos_kernel.h
  src/test/blockencodings_tests.cpp
  src/validation.cpp
  test/lint/lint-circular-dependencies.sh
Labels: kind/fix

#522 v1.7.10
  configure.ac
Labels: kind/chore

#532 Fix to add txid in logging for expiration of ICX order/offer/dfchtlc.
  src/validation.cpp
Labels: kind/fix

#537 Fix regression in staker block time calculation
  src/masternodes/rpc_masternodes.cpp
  src/pos.cpp
  src/pos_kernel.cpp
  src/pos_kernel.h
Labels: kind/fix

#535 Pay anchor with lowest BTC TX height first
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/test/anchor_tests.cpp
Labels: kind/fix

#539 Remove unused and obsolete system
  src/Makefile.am
  src/Makefile.test.include
  src/consensus/params.h
  src/consensus/tx_check.cpp
  src/consensus/tx_check.h
  src/consensus/tx_verify.cpp
  src/init.cpp
  src/masternodes/criminals.cpp
  src/masternodes/criminals.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/miner.h
  src/rpc/mining.cpp
  src/test/double_sign.cpp
  src/test/setup_common.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_criminals.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/test_node.py
  test/functional/test_runner.py
  test/functional/wallet_backup.py
  test/functional/wallet_hd.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/fix

#540 If anchor plus time depth more than current time then skip it
  src/masternodes/anchors.cpp
  test/functional/feature_anchor_rewards.py
Labels: kind/fix

#538 v1.7.11
  build_msvc/defi_config.h
  configure.ac
  make.sh
  share/genbuild.sh
  src/clientversion.cpp
  src/clientversion.h
Labels: kind/chore

#542 Keep minter pubkey in cache
  src/chain.h
  src/masternodes/masternodes.cpp
  src/masternodes/rpc_masternodes.cpp
  src/primitives/block.h
  src/test/pos_tests.cpp
Labels: kind/fix

#543 Do db compacting after undo pruning
  src/flushablestorage.h
  src/validation.cpp
Labels: kind/fix

#547 getmasternodeblocks add single quote to help text
  src/masternodes/rpc_masternodes.cpp
Labels: kind/fix, needs/kind

#548 Reduce output from getblocktemplate
  src/rpc/blockchain.cpp
  test/functional/feature_bip68_sequence.py
  test/functional/feature_cltv.py
  test/functional/feature_csv_activation.py
  test/functional/feature_dersig.py
  test/functional/p2p_compactblocks.py
  test/functional/p2p_segwit.py
  test/functional/p2p_segwit2.py
  test/functional/rpc_blockchain.py
  test/functional/test_framework/util.py
Labels: kind/chore

#553 Show the amount value if amount not match
  src/masternodes/mn_checks.cpp
  test/functional/feature_icx_orderbook_errors.py
Labels: kind/fix

#556 On HTLC creation get last weeks filtered blocks
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRPeerManager.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
Labels: kind/fix

#531 Take anchor block deeper to avoid "Anchor too new" error
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/anchors.cpp
  src/validation.cpp
  test/functional/feature_anchor_rewards.py
  test/functional/feature_anchorauths_pruning.py
Labels: kind/fix

#560 Use actual blocktime when storing TX.
  src/spv/bitcoin/BRPeerManager.cpp
Labels: kind/fix, needs/kind

#558 Show addresses not script hex in getcustomtx
  src/masternodes/rpc_customtx.cpp
  src/test/rpc_tests.cpp
  test/functional/rpc_getcustomtx.py
Labels: kind/fix

#561 Set anchor DB version and wipe it and SPV DB on version change
  src/dbwrapper.h
  src/init.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
Labels: kind/feature

#570 Fix connection issues on Windows
  src/spv/bitcoin/BRPeer.cpp
  src/spv/bitcoin/BRPeerManager.h
Labels: kind/fix
