Repository DeFiCh/ain, pull requests merged in 2021-11, with the labels that each got.

#857 Add interest before batch splitting to prevent disproportion
  src/validation.cpp
  test/functional/feature_loan_auctions.py
Labels: kind/fix

#860 Refactor GetLoanCollaterals, loan naming conventions to be consistent
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  src/test/loan_tests.cpp
  src/validation.cpp
Labels: kind/refactor

#862 Prevent takeloan if DFI collateral is less than 50%.
  src/masternodes/mn_checks.cpp
  test/functional/feature_loan_deposittovault.py
  test/functional/feature_loan_vault.py
Labels: kind/fix

#861 Add verbose parameter to listvaults
  src/masternodes/rpc_vault.cpp
Labels: kind/fix

#863 Return precision loss collateral balanced
  src/validation.cpp
  test/functional/feature_loan_auctions.py
Labels: kind/feature

#864 Additional functional tests for auction batches
  test/functional/feature_loan_auctions.py
Labels: kind/chore

#865 Readability
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
Labels: kind/chore

#867 Fix active/nextprice block calculation
  src/masternodes/rpc_oracles.cpp
  test/functional/feature_loan_priceupdate.py
Labels: kind/fix

#868 Remove obsolete compatibility
  src/net.cpp
Labels: kind/chore

#875 Prevent selecting auto auth outputs
  src/masternodes/mn_rpc.cpp
  src/wallet/wallet.cpp
Labels: kind/fix, needs/kind

#872 Fix pool share rewards regression
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#874 Add all new FC and Oracle DfTx to getcustomtx tests
  src/masternodes/rpc_customtx.cpp
  test/functional/rpc_getcustomtx.py
Labels: kind/chore

#878 Disable minting loan token on mainnet
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#879 Sync nodes before check
  test/functional/feature_anchor_rewards.py
Labels: kind/fix

#871 Restore previous getgov behaviour
  src/masternodes/mn_rpc.cpp
  test/functional/feature_icx_orderbook.py
  test/functional/feature_icx_orderbook_errors.py
  test/functional/feature_poolswap_mechanism.py
  test/functional/feature_setgov.py
Labels: kind/chore

#877 Fix typo in listauctionhistory
  src/masternodes/rpc_vault.cpp
Labels: kind/chore

#881 Fix rpc_vault HelpExampleRpc messages
  src/masternodes/rpc_vault.cpp
Labels: kind/chore

#880 Fix pagination issue
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_vault.cpp
Labels: kind/fix, area/rpc

#876 Fix new regression
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#883 Fix HelpExampleRpc messages
  src/masternodes/rpc_vault.cpp
Labels: kind/chore

#887 Don't show zero rewards
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#889 Remerge missing rpc_vault HelpExampleRpc
  src/masternodes/rpc_vault.cpp
Labels: kind/fix

#890 Revert history records
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#891 Version 2.1.0
  configure.ac
Labels: kind/chore

#892 Bump protocol version to 70021
  src/version.h
Labels: kind/chore

#894 Add Great World fork height
  configure.ac
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/rpc/blockchain.cpp
  src/test/blockencodings_tests.cpp
  test/functional/rpc_blockchain.py
Labels: kind/feature

#888 Remove redundant isNull check on RPCArg::Optional::No arguments
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
Labels: kind/chore

#886 Refactor rpc oracles
  src/masternodes/rpc_oracles.cpp
Labels: kind/refactor

#896 Use mocktime in deposittovault tests
  test/functional/feature_loan_deposittovault.py
Labels: kind/fix

#901 Disable updatemasternode, and reward address change
  configure.ac
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_masternodes.cpp
  src/version.h
Labels: kind/chore

#902 Update failing tests for recent changes
  test/functional/feature_update_mn.py
  test/functional/rpc_getcustomtx.py
  test/functional/test_runner.py
Labels: kind/fix

#905 Fix RPC help and test failure
  src/masternodes/rpc_masternodes.cpp
  test/functional/feature_forced_reward_address.py
Labels: kind/fix

#906 Prevent vaults iteration on every block
  src/validation.cpp
Labels: kind/fix

#900 Fix test deposittovault
  test/functional/feature_loan_deposittovault.py
Labels: kind/fix

#911 Revert auto auth selecting protection
  src/wallet/wallet.cpp
Labels: kind/fix

#908 Add liquidation of DUSD in basic test
  test/functional/feature_loan_basics.py
Labels: kind/chore, area/loan

#918 [Testing] Enable hotfixes branch
  .github/workflows/hotfix-builds.yaml
  make.sh
  share/genbuild.sh
Labels: needs/kind

#898 Add vault history DB and listvaulthistory RPC call
  src/Makefile.am
  src/init.cpp
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/loan.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_vault.cpp
  src/masternodes/vaulthistory.cpp
  src/masternodes/vaulthistory.h
  src/rpc/client.cpp
  src/validation.cpp
  test/functional/rpc_listvaulthistory.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/feature
