Repository DeFiCh/ain, pull requests merged in 2021-12, with the labels that each got.

#895 Fix updateloantoken arguments parsing and description
  src/masternodes/rpc_loan.cpp
  src/rpc/client.cpp
Labels: kind/fix

#899 Refactor JSON response preventing unnecessary copies
  src/httprpc.cpp
  src/rpc/request.cpp
  src/rpc/request.h
  src/rpc/server.cpp
  src/rpc/server.h
Labels: kind/refactor

#893 Remove dead code
  src/masternodes/balances.h
  src/masternodes/poolpairs.h
  src/masternodes/res.h
  src/masternodes/rpc_poolpair.cpp
Labels: kind/chore

#932 Use height based on hashPrevBlock
  src/test/blockencodings_tests.cpp
  src/validation.cpp
Labels: kind/bug

#933 Adds estimatevault RPC
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/rpc_vault.cpp
  src/rpc/client.cpp
  test/functional/feature_loan_vault.py
Labels: kind/feature

#915 Add optional vaultId input parameter to listauctionhistory
  src/masternodes/rpc_vault.cpp
  src/rpc/rawtransaction_util.cpp
  src/rpc/rawtransaction_util.h
  test/functional/feature_loan.py
Labels: kind/feature

#931 Erase vault history loan scheme records
  src/masternodes/vaulthistory.cpp
Labels: kind/fix

#927 Adds estimatecollateral RPC
  src/masternodes/rpc_vault.cpp
  src/rpc/client.cpp
  test/functional/feature_loan_estimatecollateral.py
  test/functional/test_runner.py
Labels: kind/feature

#936 Well define masternode states
  src/masternodes/anchors.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/rpc/mining.cpp
  src/validation.cpp
Labels: kind/refactor

#909 Add "mine" option to listvaults
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan_vault.py
Labels: kind/fix

#873 getcustomtxcodes RPC
  src/masternodes/rpc_accounts.cpp
  test/functional/rpc_getcustomtxcodes.py
  test/functional/test_runner.py
Labels: kind/feature

#950 Prefer tx entry time order for a block
  src/miner.cpp
  src/miner.h
Labels: kind/feature

#919 Fix build suffix for all branches and introduce hotfix
  .github/workflows/hotfix-builds.yaml
  contrib/dockerfiles/arm-linux-gnueabihf.dockerfile
  contrib/dockerfiles/x86_64-apple-darwin11.dockerfile
  contrib/dockerfiles/x86_64-pc-linux-gnu.dockerfile
  contrib/dockerfiles/x86_64-w64-mingw32.dockerfile
  make.sh
  share/genbuild.sh
Labels: kind/chore

#955 Revert "Use height based on hashPrevBlock (#932)"
  src/test/blockencodings_tests.cpp
  src/validation.cpp
Labels: kind/bug

#960 Add latest hotfix changes into master
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/miner.cpp
  src/rpc/blockchain.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_loan_interest.py
  test/functional/feature_loan_priceupdate.py
  test/functional/rpc_blockchain.py
  test/functional/test_runner.py
Labels: kind/fix

#942 Interest calculation improvements to ceil interest to next sats
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/rpc/blockchain.cpp
  test/functional/feature_loan_interest.py
  test/functional/feature_loan_priceupdate.py
  test/functional/rpc_blockchain.py
  test/functional/test_runner.py
Labels: consensus, kind/feature, area/loan

#963 Version 2.3.0
  configure.ac
Labels: kind/chore

#969 Restore int behaviour pre-FCM
  src/masternodes/loan.cpp
Labels: kind/chore

#966 Restore owner calc behaviour
  src/validation.cpp
Labels: kind/fix

#986 Fix wrong number of openVaults and openAuctions in getloaninfo
  src/masternodes/rpc_loan.cpp
Labels: kind/fix

#997 Fix boost 1.77 compilation
  src/wallet/test/db_tests.cpp
  src/wallet/test/init_test_fixture.cpp
Labels: kind/fix

#987 Factor out usage of height field in CBlockIndex and CBlockHeader
  src/bench/checkblock.cpp
  src/bench/duplicate_inputs.cpp
  src/blockencodings.cpp
  src/blockencodings.h
  src/chain.h
  src/chainparams.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/net_processing.cpp
  src/pos.cpp
  src/pos.h
  src/primitives/block.cpp
  src/primitives/block.h
  src/test/blockencodings_tests.cpp
  src/test/pos_tests.cpp
  src/test/setup_common.cpp
  src/txdb.cpp
  src/validation.cpp
  src/validation.h
Labels: kind/fix

#937 Adds possibility to use "*" to auto-select address in placeauctionbid and paybackloan
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan.py
  test/functional/feature_loan_basics.py
Labels: kind/feature

#921 Add start BTC height and record limit to spv_listanchors
  src/rpc/client.cpp
  src/spv/spv_rpc.cpp
Labels: kind/feature

#904 Rework mempool accounts view
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  test/functional/rpc_mn_basic.py
Labels: kind/fix

#954 Enable composite swap for `testpoolswap`
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_poolpair.cpp
  src/rpc/client.cpp
  test/functional/feature_poolswap.py
  test/functional/feature_poolswap_composite.py
Labels: kind/feature

#1000 Version 2.3.2
  configure.ac
Labels: kind/chore

#1003 Fix excess logging of composite swap
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_poolpair.cpp
Labels: kind/fix

#1004 Add support for test only composite swap without balance transfers
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_poolpair.cpp
Labels: kind/feature

#1005 Adds FortCanningHillHeight
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/rpc/blockchain.cpp
  test/functional/rpc_blockchain.py
Labels: kind/feature
