Repository DeFiCh/ain, pull requests merged in 2022-07, with the labels that each got.

#1372 [Testing] 2.8.1 with log account balances
  src/masternodes/rpc_accounts.cpp
  src/rpc/client.cpp
Labels: kind/chore, DO-NOT-MERGE

#1370 Revert commissions fix, updates logaccountbalances
  src/masternodes/poolpairs.cpp
  src/masternodes/rpc_accounts.cpp
  test/functional/feature_commission_fix.py
  test/functional/test_runner.py
Labels: kind/chore

#1373 Version 2.9.1
  configure.ac
Labels: kind/chore

#1349 Remove Boost Thread and Chrono
  build-aux/m4/ax_boost_chrono.m4
  build-aux/m4/ax_boost_thread.m4
  build_msvc/defi_config.h
  ci/test/00_setup_env_amd64_asan.sh
  ci/test/00_setup_env_amd64_fuzz.sh
  ci/test/00_setup_env_amd64_trusty.sh
  ci/test/00_setup_env_amd64_tsan.sh
  configure.ac
  depends/packages/boost.mk
  doc/build-unix.md
  src/addrman.cpp
  src/bench/checkqueue.cpp
  src/bench/examples.cpp
  src/chainparams.cpp
  src/checkqueue.h
  src/defi-cli.cpp
  src/defid.cpp
  src/flushablestorage.h
  src/httprpc.cpp
  src/index/txindex.cpp
  src/init.cpp
  src/masternodes/anchors.h
  src/miner.cpp
  src/node/coinstats.cpp
  src/node/coinstats.h
  src/random.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/scheduler.cpp
  src/scheduler.h
  src/script/sigcache.cpp
  src/spv/bitcoin/BRPeer.cpp
  src/spv/bitcoin/BRPeer.h
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRPeerManager.h
  src/spv/bitcoin/BRWallet.cpp
  src/spv/spv_wrapper.h
  src/test/checkqueue_tests.cpp
  src/test/cuckoocache_tests.cpp
  src/test/oracles_tests.cpp
  src/test/reverselock_tests.cpp
  src/test/scheduler_tests.cpp
  src/test/setup_common.cpp
  src/test/setup_common.h
  src/test/storage_tests.cpp
  src/test/transaction_tests.cpp
  src/test/util_tests.cpp
  src/txdb.cpp
  src/util/system.h
  src/util/time.cpp
  src/util/time.h
  src/validation.cpp
  src/validation.h
  src/wallet/db.cpp
  src/wallet/walletdb.cpp
  test/lint/lint-includes.sh
Labels: kind/chore

#1362 Separate undo database from account database
  src/flushablestorage.h
  src/init.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/undo.h
  src/masternodes/undos.cpp
  src/masternodes/undos.h
  src/miner.cpp
  src/test/setup_common.cpp
  src/test/storage_tests.cpp
  src/validation.cpp
  src/validation.h
  test/functional/test_framework/test_framework.py
Labels: kind/chore

#1343 Restore updatemasternode
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/masternodes/anchors.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/pos.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/test/blockencodings_tests.cpp
  src/test/pos_tests.cpp
  src/test/setup_common.cpp
  src/txdb.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/validation.h
  test/functional/feature_update_mn.py
  test/functional/rpc_getcustomtx.py
  test/functional/rpc_updatemasternode.py
  test/functional/test_runner.py
Labels: kind/feature

#1346 TX version and expiration
  src/consensus/tx_check.cpp
  src/consensus/tx_check.h
  src/init.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_poolpair.cpp
  src/primitives/transaction.h
  src/rpc/client.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  test/functional/feature_reject_customtxs.py
  test/functional/feature_tx_versioning_and_expiration.py
  test/functional/test_runner.py
Labels: kind/feature

#1381 Migrate undos to dedicated DB
  src/flushablestorage.h
  src/init.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/undo.h
  src/masternodes/undos.cpp
  src/masternodes/undos.h
  src/miner.cpp
  src/test/setup_common.cpp
  src/test/storage_tests.cpp
  src/validation.cpp
  src/validation.h
  test/functional/test_framework/test_framework.py
Labels: kind/feature

#1392 Fix swap when direct path disabled
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolswap_composite.py
Labels: kind/fix

#1391 Order getmasternodeblocks results
  src/masternodes/masternodes.h
  src/masternodes/rpc_masternodes.cpp
Labels: kind/feature

#1388 Order getmasternodeblocks results
  src/masternodes/masternodes.h
  src/masternodes/rpc_masternodes.cpp
Labels: kind/fix

#1393 Version 2.9.2
  configure.ac
Labels: kind/chore

#1396 Remove Boost Thread and Chrono
  build-aux/m4/ax_boost_chrono.m4
  build-aux/m4/ax_boost_thread.m4
  build_msvc/defi_config.h
  ci/test/00_setup_env_amd64_asan.sh
  ci/test/00_setup_env_amd64_fuzz.sh
  ci/test/00_setup_env_amd64_trusty.sh
  ci/test/00_setup_env_amd64_tsan.sh
  configure.ac
  depends/packages/boost.mk
  doc/build-unix.md
  src/addrman.cpp
  src/bench/checkqueue.cpp
  src/bench/examples.cpp
  src/chainparams.cpp
  src/checkqueue.h
  src/defi-cli.cpp
  src/defid.cpp
  src/flushablestorage.h
  src/httprpc.cpp
  src/index/txindex.cpp
  src/init.cpp
  src/masternodes/anchors.h
  src/miner.cpp
  src/node/coinstats.cpp
  src/node/coinstats.h
  src/random.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/scheduler.cpp
  src/scheduler.h
  src/script/sigcache.cpp
  src/spv/bitcoin/BRPeer.cpp
  src/spv/bitcoin/BRPeer.h
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRPeerManager.h
  src/spv/bitcoin/BRWallet.cpp
  src/spv/spv_wrapper.h
  src/test/checkqueue_tests.cpp
  src/test/cuckoocache_tests.cpp
  src/test/oracles_tests.cpp
  src/test/reverselock_tests.cpp
  src/test/scheduler_tests.cpp
  src/test/setup_common.cpp
  src/test/setup_common.h
  src/test/storage_tests.cpp
  src/test/transaction_tests.cpp
  src/test/util_tests.cpp
  src/txdb.cpp
  src/util/system.h
  src/util/time.cpp
  src/util/time.h
  src/validation.cpp
  src/validation.h
  src/wallet/db.cpp
  src/wallet/walletdb.cpp
  test/lint/lint-includes.sh
Labels: kind/chore

#1394 Fix for testpoolswap auto selection on disabled pools
  src/masternodes/rpc_poolpair.cpp
Labels: kind/fix

#1399 Mocknet create MN on start
  src/init.cpp
  src/pos.cpp
Labels: kind/feature
