Repository DeFiCh/ain, pull requests merged in 2022-10, with the labels that each got.

#1483 Replace hashlib.ripemd160 with an pure Python implementation
  test/functional/test_framework/ripemd160.py
  test/functional/test_framework/script.py
Labels: kind/fix

#1498 Update CODEOWNERS
  .github/CODEOWNERS
Labels: kind/chore

#1510 update Bitcoin DNS seeds
  src/spv/bitcoin/BRChainParams.cpp
Labels: kind/chore

#1505 Pool commission/reward fix
  src/masternodes/poolpairs.cpp
  test/functional/feature_commission_fix.py
  test/functional/test_runner.py
Labels: kind/fix

#1481 Fix compositeswap to use direct pool when available and fix testpoolswap calculation
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolswap_composite.py
  test/functional/feature_testpoolswap.py
  test/functional/test_runner.py
Labels: kind/fix

#1466 Exclude accountchange debug category from python test
  test/functional/test_framework/test_node.py
Labels: kind/chore

#1516 Do not suppress errors for simple swaps on testpoolswap
  src/masternodes/rpc_poolpair.cpp
Labels: kind/fix

#1514 Adds argument `-leveldbchecksum`
  src/dbwrapper.cpp
  src/init.cpp
  src/masternodes/mn_checks.cpp
  test/functional/feature_on_chain_government.py
  test/lint/check-doc.py
Labels: kind/feature

#1521 Revert "Adds argument `-leveldbchecksum`"
  src/dbwrapper.cpp
  src/init.cpp
  src/masternodes/mn_checks.cpp
  test/functional/feature_on_chain_government.py
  test/lint/check-doc.py
Labels: needs/kind

#1515 Skip collateral factor check
  src/init.cpp
  src/masternodes/govvariables/attributes.cpp
  test/functional/feature_skip_collateral_factor_check.py
  test/functional/test_runner.py
Labels: kind/feature

#1527 Run Dev Build and Jellyfish tests on `epic/*` branches
  .github/workflows/dev-builds.yaml
  .github/workflows/jellyfish-tests.yml
Labels: kind/chore

#1528 Backport of `Throw error on pairSymbol larger than expected` (#1069)
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolpair.py
Labels: kind/fix

#1530 Skip jellyfish tests on master
  .github/workflows/jellyfish-tests.yml
Labels: kind/chore

#1531 Implementation of DFIP-2208-C
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_proposals.cpp
  src/validation.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_fee_distribution.py
  test/functional/test_runner.py
Labels: kind/feature
