Repository DeFiCh/ain, pull requests merged in 2022-04, with the labels that each got.

#1190 Merge v3
  .dockerignore
  src/chainparams.cpp
  src/interfaces/chain.cpp
  src/interfaces/chain.h
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/consensus/loans.cpp
  src/masternodes/consensus/smartcontracts.cpp
  src/masternodes/customtx.cpp
  src/masternodes/customtx.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_oracles.cpp
  src/rpc/client.cpp
  src/rpc/rawtransaction_util.cpp
  src/validation.cpp
  src/version.h
  test/functional/feature_futures.py
  test/functional/feature_setgov.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/fix

#1193 Revert "Fix dex loan token burns"
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#1199 Set correct values for TokenKeys
  src/masternodes/govvariables/attributes.h
Labels: kind/chore

#1200 Simplify attribute key uint32 migration
  src/masternodes/govvariables/attributes.h
Labels: kind/fix

#1007 Calculate collateral ratio when there is actual price update
  src/validation.cpp
Labels: enhancement, kind/fix, 3.0.0

#1182 Increase LRU cache, limit write buffer
  src/dbwrapper.cpp
Labels: kind/fix

#1181 Invalidate block at any time
  src/rpc/blockchain.cpp
  src/validation.cpp
  test/functional/interface_rest.py
  test/functional/mempool_packages.py
  test/functional/rpc_blockchain.py
  test/functional/rpc_invalidateblock.py
  test/functional/rpc_rawtransaction.py
Labels: kind/feature

#1212 Fix typos
  src/masternodes/icxorder.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_vault.cpp
Labels: kind/fix

#1192 Live dex statistics
  src/masternodes/consensus/loans.cpp
  src/masternodes/consensus/smartcontracts.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/gv.cpp
  src/masternodes/mn_checks.cpp
  src/validation.cpp
  test/functional/feature_loan_vault.py
  test/functional/feature_poolswap.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/feature

#1204 Update test cases to remove `deprecatedHeight` usage.
  src/test/blockencodings_tests.cpp
Labels: kind/fix

#1203 Add -isysroot to macOS native compile flags
  depends/builders/darwin.mk
Labels: kind/fix

#1211 Add version suffix to getversioninfo
  src/clientversion.cpp
  src/clientversion.h
  src/rpc/net.cpp
Labels: kind/fix

#1180 Add CustomTxType FromString method
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_accounts.cpp
  test/functional/rpc_listaccounthistory.py
Labels: kind/feature

#1130 Add valgrind to test framework
  contrib/valgrind.supp
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/test_node.py
Labels: kind/feature

#1183 Test/payback v2 multiple error
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_loan_payback_dfi_v2.py
  test/functional/feature_poolswap_mainnet.py
Labels: kind/fix
