Repository DeFiCh/ain, pull requests merged in 2022-12, with the labels that each got.

#1465 Refactor consensus with contract based predicates
  src/amount.h
  src/chainparams.cpp
  src/masternodes/accounts.cpp
  src/masternodes/balances.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/loan_daily_reward.cpp
  src/masternodes/govvariables/loan_liquidation_penalty.cpp
  src/masternodes/govvariables/loan_splits.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/masternodes/govvariables/lp_splits.cpp
  src/masternodes/govvariables/oracle_block_interval.cpp
  src/masternodes/govvariables/oracle_deviation.cpp
  src/masternodes/gv.cpp
  src/masternodes/icxorder.cpp
  src/masternodes/incentivefunding.cpp
  src/masternodes/loan.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/oracles.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/res.h
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/masternodes/vault.cpp
  src/rpc/rawtransaction_util.cpp
  src/test/util_tests.cpp
  src/validation.cpp
  test/functional/feature_autoauth.py
  test/functional/feature_loan_scheme.py
  test/functional/feature_loan_vault.py
  test/functional/feature_tokens_multisig.py
Labels: kind/chore, ci/sync

#1614 Refactor fork check
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/poolpairs.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_poolpair.cpp
Labels: kind/chore, ci/sync

#1636 test: Remove fragile assert_memory_usage_stable
  test/functional/p2p_invalid_messages.py
  test/functional/test_framework/test_node.py
Labels: kind/fix

#1637 Reduce range to previous value
  test/functional/p2p_invalid_messages.py
Labels: kind/fix

#1641 Add undo in ReversGeneralCoinbaseTx()
  src/validation.cpp
Labels: kind/fix

#1642 Version v3.1.1
  configure.ac
  src/version.h
Labels: kind/chore

#1645 test: Remove fragile assert_memory_usage_stable
  test/functional/p2p_invalid_messages.py
  test/functional/test_framework/test_node.py
Labels: kind/fix

#1644 Refactor consensus with contract based predicates
  src/amount.h
  src/chainparams.cpp
  src/masternodes/accounts.cpp
  src/masternodes/balances.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/loan_daily_reward.cpp
  src/masternodes/govvariables/loan_liquidation_penalty.cpp
  src/masternodes/govvariables/loan_splits.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/masternodes/govvariables/lp_splits.cpp
  src/masternodes/govvariables/oracle_block_interval.cpp
  src/masternodes/govvariables/oracle_deviation.cpp
  src/masternodes/gv.cpp
  src/masternodes/icxorder.cpp
  src/masternodes/incentivefunding.cpp
  src/masternodes/loan.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/oracles.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/res.h
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/masternodes/vault.cpp
  src/rpc/rawtransaction_util.cpp
  src/test/util_tests.cpp
  src/validation.cpp
  test/functional/feature_autoauth.py
  test/functional/feature_loan_scheme.py
  test/functional/feature_loan_vault.py
  test/functional/feature_tokens_multisig.py
Labels: kind/chore, ci/sync

#1629 chore(libmc.mk): get architecture from script
  depends/packages/libain.mk
  depends/packages/libmc.mk
  depends/rust_target.sh
Labels: kind/chore

#1625 chore(osx_docs): install instructions for rust toolchain + protobuf compiler
  doc/build-osx.md
Labels: kind/chore

#1648 Refactor fork check
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/poolpairs.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_poolpair.cpp
Labels: kind/chore, ci/sync

#1652 Revert "Update Bitcoin DNS seeds (#1545)"
  src/spv/bitcoin/BRChainParams.cpp
Labels: kind/fix

#1657 Add GrandCentralNext fork
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/rpc/blockchain.cpp
  test/functional/rpc_blockchain.py
Labels: kind/feature

#1661 Convert devnet into mirror testnet
  src/chainparams.cpp
  src/chainparamsbase.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/pos.cpp
  src/util/system.cpp
Labels: kind/feature, v/3.2.0

#1654 On-chain governance fixes
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/proposals.cpp
  src/masternodes/rpc_proposals.cpp
  src/validation.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_govvar_update.py
Labels: kind/fix, v/3.2.0

#1670 v3.2.0-rc1
  configure.ac
  src/chainparams.cpp
  src/version.h
Labels: kind/chore

#1668 Refactor consensus with contract based predicates
  src/amount.h
  src/chainparams.cpp
  src/masternodes/accounts.cpp
  src/masternodes/balances.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/loan_daily_reward.cpp
  src/masternodes/govvariables/loan_liquidation_penalty.cpp
  src/masternodes/govvariables/loan_splits.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/masternodes/govvariables/lp_splits.cpp
  src/masternodes/govvariables/oracle_block_interval.cpp
  src/masternodes/govvariables/oracle_deviation.cpp
  src/masternodes/gv.cpp
  src/masternodes/icxorder.cpp
  src/masternodes/incentivefunding.cpp
  src/masternodes/loan.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/oracles.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/res.h
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/masternodes/vault.cpp
  src/rpc/rawtransaction_util.cpp
  src/test/util_tests.cpp
  src/validation.cpp
  test/functional/feature_autoauth.py
  test/functional/feature_loan_scheme.py
  test/functional/feature_loan_vault.py
  test/functional/feature_tokens_multisig.py
Labels: kind/chore

#1672 Resolve getcustomtx call with updatemasternode on owner transfer
  src/masternodes/rpc_customtx.cpp
  test/functional/rpc_updatemasternode.py
Labels: kind/fix

#1673 Set GrandCentralEpilogue release
  configure.ac
  src/chainparams.cpp
Labels: kind/chore

#1677 Add more examples in minttokens help dialogue
  src/masternodes/rpc_tokens.cpp
Labels: kind/fix, v/3.2.1

#1660 Add test for changing voting period before previous period ending.
  test/functional/feature_on_chain_government_voting_period_alignment.py
  test/functional/test_runner.py
Labels: kind/chore, area/governance, v/3.2.1

#1647 Input validation of creategovvoc and creategovcfp
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/fix, v/3.2.1
