Repository DeFiCh/ain, pull requests merged in 2022-11, with the labels that each got.

#1538 Add feature flags and GrandCentral fork
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/rpc/blockchain.cpp
  test/functional/rpc_blockchain.py
Labels: kind/feature

#1523 Update CI full sync to use available snapshots
  .github/workflows/fullsync-tests.yml
  ci/parallel_sync/sync_then_diff.sh
Labels: kind/feature, ci/sync

#1542 Pull bdb, libevent, miniupnpc upstream updates
  depends/packages/bdb.mk
  depends/packages/libevent.mk
  depends/packages/miniupnpc.mk
  depends/patches/bdb/clang_cxx_11.patch
  depends/patches/miniupnpc/dont_leak_info.patch
  depends/patches/miniupnpc/respect_mingw_cflags.patch
Labels: kind/chore

#1522 Unset Governance variables
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/icx_takerfee_per_btc.h
  src/masternodes/govvariables/loan_daily_reward.cpp
  src/masternodes/govvariables/loan_daily_reward.h
  src/masternodes/govvariables/loan_liquidation_penalty.cpp
  src/masternodes/govvariables/loan_liquidation_penalty.h
  src/masternodes/govvariables/loan_splits.cpp
  src/masternodes/govvariables/loan_splits.h
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.h
  src/masternodes/govvariables/lp_splits.cpp
  src/masternodes/govvariables/lp_splits.h
  src/masternodes/govvariables/oracle_block_interval.cpp
  src/masternodes/govvariables/oracle_block_interval.h
  src/masternodes/govvariables/oracle_deviation.cpp
  src/masternodes/govvariables/oracle_deviation.h
  src/masternodes/gv.cpp
  src/masternodes/gv.h
  src/masternodes/icxorder.cpp
  src/masternodes/icxorder.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/oracles.cpp
  src/masternodes/oracles.h
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/rpc_customtx.cpp
  src/rpc/client.cpp
  test/functional/feature_setgov.py
Labels: kind/feature

#1544 Add empty string check for tokenTo and tokenFrom in testpoolswap
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolswap.py
Labels: kind/fix

#1549 Add test for govvar update between proposal cycles
  src/masternodes/proposals.cpp
  src/masternodes/rpc_customtx.cpp
  src/validation.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_govvar_update.py
  test/functional/test_runner.py
Labels: kind/chore, v/3.0.0

#1545 Update Bitcoin DNS seeds
  src/spv/bitcoin/BRChainParams.cpp
Labels: kind/chore, v/3.0.0

#1546 Backport of `Throw error on pairSymbol larger than expected` (#1069)
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolpair.py
Labels: kind/fix, v/3.0.0

#1520 Change OP_RETURN data size
  src/script/standard.h
  src/test/transaction_tests.cpp
Labels: kind/feature, v/3.0.0

#1547 Reject swaps when output token does not match toToken
  src/masternodes/mn_checks.cpp
  test/functional/feature_poolswap_composite.py
Labels: kind/fix, v/3.0.0

#1501 Update repository on jellyfish test workflow
  .github/workflows/jellyfish-tests.yml
Labels: kind/fix, v/3.0.0

#1512 Fix collateral factor not taken into account on vault requirement checks
  src/init.cpp
  src/masternodes/mn_checks.cpp
  test/functional/feature_vault_pct_check_factor.py
  test/functional/test_runner.py
Labels: kind/fix, v/3.0.0

#1476 Fix feature_poolswap_composite test crashing node.
  src/masternodes/rpc_customtx.cpp
Labels: kind/fix, area/dex

#1484 Provide better error message for max pool swaps
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolswap_composite.py
Labels: kind/chore, v/3.0.0

#1550 Migrate stored Gov var unlock on split
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/mn_checks.cpp
  src/validation.cpp
  test/functional/feature_split_migrate_lock.py
  test/functional/test_runner.py
Labels: kind/feature, v/3.0.0

#1540 Migrate foundation addresses to Governance variables
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  src/masternodes/rpc_tokens.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_foundation_migration.py
  test/functional/test_runner.py
Labels: kind/feature, v/3.0.0

#1552 Skip token locked check
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/oracles.cpp
  src/masternodes/oracles.h
  src/masternodes/rpc_vault.cpp
  test/functional/feature_token_lock.py
  test/functional/feature_token_split_usd_value.py
Labels: kind/fix, v/3.0.0

#1553 Fix CI deprecation warnings
  .github/workflows/dev-builds.yaml
  .github/workflows/lint.yaml
  .github/workflows/tests.yaml
Labels: kind/chore

#1554 Run generate-matrix job on ci/sync tag
  .github/workflows/fullsync-tests.yml
Labels: kind/chore

#1534 Poolswap to empty to address swaps to from address making to optional
  src/masternodes/mn_checks.cpp
  test/functional/feature_poolswap.py
Labels: kind/fix, v/3.0.0

#1537 Add updatemasternode RPC call
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/masternodes/anchors.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/pos.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/test/blockencodings_tests.cpp
  src/test/pos_tests.cpp
  src/test/setup_common.cpp
  src/txdb.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/validation.h
  test/functional/feature_accounts_n_utxos.py
  test/functional/feature_update_mn.py
  test/functional/rpc_getcustomtx.py
  test/functional/rpc_updatemasternode.py
  test/functional/test_runner.py
Labels: kind/feature, v/3.0.0

#1551 Track loan DUSD in live economy
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/validation.cpp
  test/functional/feature_loan_payback_dfi.py
Labels: kind/chore

#1486 Fix incorrect start index behaviour in listprices RPC
  doc/build-osx.md
  src/masternodes/rpc_oracles.cpp
  test/functional/feature_oracles.py
Labels: kind/fix, v/3.0.0

#1339 Add versionSuffix getversioninfo
  src/clientversion.cpp
  src/clientversion.h
  src/rpc/net.cpp
Labels: kind/fix, v/3.0.0

#1541 Consortium implementation
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_tokens.cpp
  src/rpc/client.cpp
  test/functional/feature_consortium.py
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_loan_payback_dfi_v2.py
  test/functional/feature_setgov.py
  test/functional/feature_skip_collateral_factor_check.py
  test/functional/test_runner.py
Labels: consensus, kind/feature, v/3.0.0

#1555 v3.0.0
  configure.ac
  src/version.h
Labels: kind/chore

#1556 Mark Grand Central Testnet
  configure.ac
  src/chainparams.cpp
Labels: kind/chore

#1557 Revert "Add versionSuffix getversioninfo"
  src/clientversion.cpp
  src/clientversion.h
  src/rpc/net.cpp
Labels: needs/kind

#1560 Update full sync CI
  .github/workflows/fullsync-tests.yml
  ci/parallel_sync/sync_then_diff.sh
Labels: kind/fix

#1562 Fix CI full sync test
  .github/workflows/fullsync-tests.yml
  ci/parallel_sync/sync_then_diff.sh
  src/masternodes/govvariables/attributes.cpp
Labels: kind/fix, ci/sync

#1559 Do not check cumulative before FCC
  src/masternodes/mn_checks.cpp
Labels: kind/fix, ci/sync

#1548 Migrate tokens in futures live economy balances
  src/validation.cpp
  test/functional/feature_migrate_v1_in_futures.py
  test/functional/test_runner.py
Labels: kind/fix, v/3.0.0

#1567 Move Gov var to feature category
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/validation.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_govvar_update.py
Labels: kind/chore

#1566 Revert change to stake modifier
  src/miner.cpp
  src/pos.cpp
  src/test/pos_tests.cpp
  src/validation.cpp
Labels: kind/fix

#1563 Discard reconsiderblock failure on full sync CI
  .github/workflows/fullsync-tests.yml
  ci/parallel_sync/sync_then_diff.sh
Labels: kind/fix

#1569 Fix percentage support in attributes
  src/masternodes/govvariables/attributes.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_poolswap.py
  test/functional/feature_setgov.py
  test/functional/rpc_updatemasternode.py
Labels: kind/fix

#1564 Move test to extended and increase timeout
  test/functional/feature_on_chain_government_govvar_update.py
  test/functional/test_runner.py
Labels: kind/fix

#1570 Full sync CI generate-matrix job remove last available snapshot
  .github/workflows/fullsync-tests.yml
Labels: kind/fix

#1572 Use correct key to computer stake modifier
  src/miner.cpp
Labels: kind/fix

#1568 Mint tokens rules adaptation
  src/init.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/rpc_tokens.cpp
  test/functional/feature_consortium.py
  test/functional/feature_foundation_migration.py
  test/functional/feature_oracles.py
  test/functional/feature_poolpair.py
  test/functional/feature_tokens_dat.py
Labels: consensus, kind/feature, area/tokens, ci/sync

#1574 Throw better errors when invalid global mint limits are set
  src/masternodes/govvariables/attributes.cpp
  test/functional/feature_consortium.py
Labels: kind/fix, v/3.0.0

#1571 Add benchmarking for custom transactions
  src/logging.cpp
  src/logging.h
  src/validation.cpp
Labels: kind/chore

#1576 Allow Consortium mint limits to be zero
  src/masternodes/govvariables/attributes.cpp
  test/functional/feature_consortium.py
Labels: kind/fix, v/3.0.0

#1533 Pool commission and reward fixes
  src/masternodes/poolpairs.cpp
  test/functional/feature_commission_fix.py
  test/functional/test_runner.py
Labels: kind/feature, v/3.0.0, ci/sync

#1575 Do not require input from new owner address
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_masternodes.cpp
  test/functional/rpc_updatemasternode.py
Labels: kind/feature

#1578 Rename minVoters to quorum
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/proposals.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_proposals.cpp
  src/validation.cpp
Labels: kind/chore

#1580 Fix minting rule
  src/masternodes/mn_checks.cpp
Labels: consensus, kind/fix, area/tokens, priority/urgent-now

#1581 Adapt autoauth tests for minttoken changes
  test/functional/feature_autoauth.py
Labels: kind/fix

#1579 Import and export consortium and foundation members as UniValue
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  test/functional/feature_consortium.py
  test/functional/feature_foundation_migration.py
  test/functional/feature_setgov.py
Labels: kind/chore

#1577 Proposal changes
  src/masternodes/mn_checks.cpp
  src/masternodes/proposals.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/fix

#1582 Fix CI builds, add rc4, upgrade proto
  .github/workflows/hotfix-builds.yaml
  .github/workflows/prune-artifacts.yaml
  .github/workflows/release-builds.yaml
  configure.ac
  src/version.h
Labels: kind/fix

#1587 Send unused emission to address
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/rpc_masternodes.cpp
  src/validation.cpp
  test/functional/feature_community_development_funds.py
Labels: kind/feature

#1583 Add fields to `getgovproposal`
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/proposals.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_proposals.cpp
  src/rpc/client.cpp
  src/validation.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_fee_distribution.py
Labels: kind/fix

#1590 Version 3.0.0-rc5
  configure.ac
  src/version.h
Labels: kind/chore

#1594 Fix BurnTokenMessage token accounting
  src/masternodes/mn_checks.cpp
Labels: kind/fix, area/tokens

#1596 Print full sync CI info
  .github/workflows/fullsync-tests.yml
  ci/parallel_sync/sync_then_diff.sh
Labels: kind/chore, ci/sync

#1595 Rename daliyMintLimit to mintLimitDaily in consortium members
  src/masternodes/govvariables/attributes.cpp
  test/functional/feature_consortium.py
  test/functional/feature_setgov.py
Labels: kind/chore

#1603 Fix testpoolswap flaky test assertion
  test/functional/feature_testpoolswap.py
Labels: kind/fix

#1599 Fix missing env variable in full sync CI
  .github/workflows/fullsync-tests.yml
  ci/parallel_sync/sync_then_diff.sh
Labels: kind/fix

#1604 Add proposal creationHeight to listgovproposals and getgovproposal
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/fix

#1597 Add emergencyPeriod and feeBurnPct to chainparams
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/masternodes.cpp
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/chore

#1607 Save quorum and majorityThreshold in proposal.
  src/masternodes/proposals.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_proposals.cpp
  src/validation.cpp
  test/functional/feature_on_chain_government_govvar_update.py
Labels: kind/feature

#1608 On-chain governance refinements and fixes
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_proposals.cpp
  src/validation.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_govvar_update.py
Labels: kind/fix

#1600 Set GrandCentral hard fork
  configure.ac
  src/chainparams.cpp
  src/version.h
Labels: kind/feature

#1610 Fix coinbase tests
  src/masternodes/rpc_customtx.cpp
  src/test/dip1fork_tests.cpp
Labels: kind/fix

#1612 Restore testnet fork height back to rc height
  configure.ac
  src/chainparams.cpp
Labels: kind/chore
