Repository DeFiCh/ain, pull requests merged in 2022-06, with the labels that each got.

#1315 Remove MakeUnique
  src/Makefile.am
  src/bench/coin_selection.cpp
  src/chainparamsbase.cpp
  src/flushablestorage.h
  src/httprpc.cpp
  src/index/blockfilterindex.cpp
  src/index/txindex.cpp
  src/init.cpp
  src/interfaces/chain.cpp
  src/interfaces/handler.cpp
  src/masternodes/icxorder.cpp
  src/masternodes/rpc_accounts.cpp
  src/net.cpp
  src/script/descriptor.cpp
  src/test/allocator_tests.cpp
  src/test/anchor_tests.cpp
  src/test/checkqueue_tests.cpp
  src/test/dbwrapper_tests.cpp
  src/test/denialofservice_tests.cpp
  src/test/fuzz/fuzz.cpp
  src/test/net_tests.cpp
  src/test/setup_common.cpp
  src/txmempool.cpp
  src/util/memory.h
  src/util/system.cpp
  src/util/system.h
  src/validation.cpp
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/load.cpp
  src/wallet/rpcdump.cpp
  src/wallet/test/coinselector_tests.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
Labels: kind/chore

#1215 Test add missing tests + fix index filtering listauctionhistory
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan.py
  test/functional/feature_loan_basics.py
  test/functional/feature_loan_scheme.py
  test/functional/feature_loan_vault.py
Labels: kind/fix

#1318 Change stop-block behavior to invalidate to ensure full validation cycle
  src/validation.cpp
Labels: kind/fix

#1325 Fix interest rate string on logs, minor refactor
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/rpc_loan.cpp
  src/test/loan_tests.cpp
  src/validation.cpp
Labels: kind/fix

#1323 Improve mocknet simulation params
  src/chainparams.cpp
Labels: kind/chore

#1322 Version 2.8.1
  configure.ac
Labels: kind/chore

#1319 Remove Boost Optional
  src/Makefile.am
  src/bench/wallet_balance.cpp
  src/chainparams.cpp
  src/flushablestorage.h
  src/interfaces/chain.cpp
  src/interfaces/chain.h
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/oracles.h
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/res.h
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/masternodes/undos.cpp
  src/masternodes/undos.h
  src/masternodes/vault.cpp
  src/masternodes/vault.h
  src/miner.cpp
  src/miner.h
  src/node/psbt.h
  src/optional.h
  src/pos.cpp
  src/pos.h
  src/primitives/block.h
  src/psbt.cpp
  src/psbt.h
  src/rpc/rawtransaction.cpp
  src/rpc/rawtransaction_util.cpp
  src/rpc/rawtransaction_util.h
  src/script/sign.h
  src/serialize_optional.h
  src/test/blockencodings_tests.cpp
  src/test/storage_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/wallet/coincontrol.h
  src/wallet/coinselection.cpp
  src/wallet/feebumper.cpp
  src/wallet/fees.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/lint/lint-includes.sh
Labels: kind/chore

#1320 Remove Boost scoped_ptr and scoped_ptr
  src/masternodes/anchors.h
  src/spv/spv_wrapper.h
  test/lint/lint-includes.sh
Labels: kind/chore

#1327 Add in-node RPC cache, optimize getloaninfo, refactor getburninfo
  src/Makefile.am
  src/httprpc.cpp
  src/init.cpp
  src/logging.cpp
  src/logging.h
  src/masternodes/masternodes.cpp
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/rpc_vault.cpp
  src/rpc/net.cpp
  src/rpc/resultcache.cpp
  src/rpc/resultcache.h
  src/validation.cpp
Labels: kind/feature

#1329 Revert "Test add missing tests + fix index filtering listauctionhistory"
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan.py
  test/functional/feature_loan_basics.py
  test/functional/feature_loan_scheme.py
  test/functional/feature_loan_vault.py
Labels: needs/kind

#1328 Move boost up to 1.77
  depends/packages/boost.mk
  src/masternodes/mn_checks.h
  src/validation.cpp
Labels: kind/chore

#1334 Replace Boost variant
  src/chainparams.cpp
  src/init.cpp
  src/key_io.cpp
  src/masternodes/anchors.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_tokens.cpp
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/rpc/util.cpp
  src/rpc/util.h
  src/script/signingprovider.cpp
  src/script/standard.cpp
  src/script/standard.h
  src/serialize.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/test/loan_tests.cpp
  src/test/script_standard_tests.cpp
  src/validation.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  test/lint/lint-includes.sh
Labels: kind/chore

#1344 Fixes type check on verbose parameter for `getvault`
  src/masternodes/rpc_vault.cpp
  src/rpc/client.cpp
Labels: kind/fix

#1345 util: Add -shutdownnotify option.
  src/init.cpp
Labels: kind/feature

#1350 Add FortCanningGardens
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/rpc/blockchain.cpp
  test/functional/rpc_blockchain.py
Labels: kind/feature

#1347 Add -checkpoints-file flag to defid
  src/chainparams.cpp
  src/chainparams.h
  src/init.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/util/strencodings.cpp
  src/util/strencodings.h
  test/lint/check-doc.py
Labels: kind/feature

#1356 Add two additional checkpoints to reduce max disk usage
  src/chainparams.cpp
Labels: kind/chore

#1348 Fix commission for first deposit after fork
  src/masternodes/poolpairs.cpp
  test/functional/feature_commission_fix.py
  test/functional/test_runner.py
Labels: kind/fix, 2.9.0

#1332 Track token and pool splits in account history
  src/flushablestorage.h
  src/init.cpp
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/masternodes/vaulthistory.h
  src/test/storage_tests.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_burn_address.py
  test/functional/feature_futures.py
  test/functional/feature_token_fork.py
  test/functional/feature_token_split.py
  test/functional/rpc_mn_basic.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/chore, 2.9.0

#1357 Burn loan interest in DUSD instead of swapping to DFI
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_accounts.cpp
  src/validation.cpp
  test/functional/feature_loan_basics.py
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_loan_payback_dfi_v2.py
  test/functional/feature_setgov.py
Labels: consensus, kind/feature, area/loan, 2.9.0

#1330 Add optional `format` flag for `listaccounthistory`
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_vault.cpp
  test/functional/feature_token_split_usd_value.py
  test/functional/rpc_getaccounthistory.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/feature, 2.9.0

#1333 Flush startup consolidation, add logaccountbalances
  src/flushablestorage.h
  src/init.cpp
  src/masternodes/rpc_accounts.cpp
  src/rpc/client.cpp
  src/rpc/resultcache.cpp
  src/rpc/resultcache.h
Labels: kind/fix, 2.9.0

#1355 DFI to DUSD FutureSwap
  src/chainparams.cpp
  src/chainparams.h
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/poolpairs.cpp
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_oracles.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_commission_fix.py
  test/functional/feature_futures.py
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_setgov.py
Labels: kind/feature, 2.9.0

#1358 Fort Canning Spring
  configure.ac
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/poolpairs.cpp
  src/rpc/blockchain.cpp
  src/validation.cpp
  test/functional/feature_asymmetric_fee.py
  test/functional/feature_commission_fix.py
  test/functional/feature_futures.py
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_setgov.py
  test/functional/rpc_blockchain.py
Labels: kind/chore, 2.9.0

#1214 Expose live dex statistics
  src/init.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/gv.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_poolswap.py
  test/functional/feature_poolswap_mainnet.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/feature, 2.9.0

#1359 Add fee_pct alias for reward_pct
  src/masternodes/govvariables/attributes.cpp
  test/functional/feature_futures.py
  test/functional/feature_loan_get_interest.py
  test/functional/feature_rpcstats.py
  test/functional/feature_setgov.py
Labels: kind/feature
