Repository DeFiCh/ain, pull requests merged in 2022-02, with the labels that each got.

#1080 Fix restore UTXO test
  src/masternodes/mn_rpc.cpp
  src/rpc/rawtransaction_util.cpp
  test/functional/feature_restore_utxo.py
Labels: kind/fix

#1093 Boost 1.71 and related upstream depends changes
  depends/Makefile
  depends/hosts/default.mk
  depends/packages/bdb.mk
  depends/packages/boost.mk
  depends/packages/native_b2.mk
  depends/packages/packages.mk
  depends/packages/zeromq.mk
Labels: kind/chore

#1099 Sync before clearing mempool
  src/masternodes/mn_rpc.cpp
  test/functional/feature_restore_utxo.py
Labels: kind/fix

#1096 Add missing cs_main lock before calling CheckPendingAnchors
  src/validation.cpp
Labels: kind/fix

#1072 Test/poolswap enhanced tests + adapt loan to mainnet parameters
  test/functional/feature_loan_vault.py
  test/functional/feature_poolswap_mainnet.py
  test/functional/test_runner.py
Labels: kind/fix

#1104 Fix pool rewards after actual share
  src/masternodes/poolpairs.cpp
  src/test/liquidity_tests.cpp
Labels: kind/fix

#1100 Fix dex loan token burns
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#1102 Implement `getaccounthistory` RPC
  src/init.cpp
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/rpc_accounts.cpp
  src/rpc/client.cpp
  test/functional/rpc_getaccounthistory.py
  test/functional/test_runner.py
Labels: kind/feature

#1101 Filter out misbehaving node
  src/net_processing.cpp
  src/validation.cpp
Labels: kind/fix

#751 Split make.sh build, fix lints, cleanup
  contrib/dockerfiles/arm-linux-gnueabihf.dockerfile
  contrib/dockerfiles/x86_64-apple-darwin11.dockerfile
  contrib/dockerfiles/x86_64-pc-linux-gnu.dockerfile
  contrib/dockerfiles/x86_64-w64-mingw32.dockerfile
  make.sh
Labels: kind/refactor

#1118 Expand dex fee capability
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolswap.py
  test/functional/feature_setgov.py
Labels: kind/feature

#1112 Wrap big endian inverted
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/auctionhistory.h
  src/masternodes/loan.h
  src/masternodes/masternodes.h
  src/masternodes/poolpairs.h
  src/masternodes/vaulthistory.h
  src/serialize.h
Labels: kind/refactor

#1113 Hard code legacy anchors
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/spv/spv_rpc.cpp
  src/test/anchor_tests.cpp
  src/validation.cpp
Labels: kind/chore

#1106 Address fund transaction slowness
  src/wallet/ismine.cpp
  src/wallet/ismine.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: kind/fix
