Repository DeFiCh/ain, pull requests merged in 2022-08, with the labels that each got.

#1401 Clone bitcoin-core/qa-assets only when running fuzz tests
  ci/test/04_install.sh
Labels: kind/fix

#1398 Prevent SPV closing sockets in use
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/spv/bitcoin/BRPeer.cpp
  src/spv/bitcoin/BRPeer.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/spv_wrapper.h
Labels: kind/fix

#1404 Make shutdown handling safer
  src/init.cpp
  src/masternodes/anchors.h
  src/spv/spv_wrapper.h
Labels: kind/fix

#1402 Fix depth argument in getmasternodeblocks
  src/masternodes/rpc_masternodes.cpp
Labels: kind/fix

#1405 Fix interestPerBlock for high precision values
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan_priceupdate.py
Labels: kind/fix

#1383 Use custom cache size anchor and SPV DBs
  src/init.cpp
Labels: kind/chore

#1384 Delete old confirms to prevent ballooning memory usage
  src/validation.cpp
  src/validation.h
Labels: kind/fix

#1406 Version 2.9.3
  configure.ac
Labels: kind/chore

#1408 Revert back to BR socket code instead of async BTC socket
  src/spv/bitcoin/BRPeer.cpp
Labels: kind/fix

#1416 Fix -stop-block and -interrupt-block crashing when used on empty -datadir
  src/validation.cpp
Labels: kind/fix

#1421 Update CODEOWNERS
  .github/CODEOWNERS
Labels: kind/chore

#1420 Log "kernel found" without debug flag
  src/miner.cpp
Labels: kind/fix

#1419 Parallel testing
  .github/workflows/automated-run.yml
  ci/parallel_sync/sync_then_diff.sh
Labels: kind/feature

#1425 Fix jellyfish test job commands
  .github/workflows/jellyfish-tests.yml
Labels: kind/fix

#1418 Explicitly specify Param type in CAmount export
  src/masternodes/govvariables/attributes.cpp
Labels: kind/fix

#1426 show debug log on success or failure
  .github/workflows/automated-run.yml
Labels: kind/fix

#1423 Negative interest rate support
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_vault.cpp
  src/rpc/util.cpp
  src/rpc/util.h
  src/test/loan_tests.cpp
  src/validation.cpp
  test/functional/feature_loan_priceupdate.py
  test/functional/feature_loan_setloantoken.py
  test/functional/feature_negative_interest.py
  test/functional/feature_negative_loan_interest.py
  test/functional/feature_setgov.py
  test/functional/feature_stored_interest.py
  test/functional/rpc_getstoredinterest.py
  test/functional/test_runner.py
Labels: kind/feature

#1429 Add `logstoredinterests`
  src/masternodes/rpc_vault.cpp
Labels: kind/feature

#1428 Fix clearmempool to clear wallet TX and refactor test rollbacks
  src/masternodes/mn_rpc.cpp
  test/functional/rpc_getstoredinterest.py
Labels: kind/fix

#1432 Add overflow check on interest rates
  src/masternodes/loan.cpp
Labels: kind/fix

#1431 Zero interest is not negative
  src/masternodes/loan.h
  src/test/loan_tests.cpp
Labels: kind/fix

#1433 Version 2.10.0
  configure.ac
  src/chainparams.cpp
Labels: kind/chore

#1435 Rename GreatWork to FortCanningGreatWorld
  .gitignore
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/loan.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  src/rpc/blockchain.cpp
  src/test/loan_tests.cpp
  src/validation.cpp
  test/functional/feature_negative_interest.py
  test/functional/feature_negative_loan_interest.py
  test/functional/feature_stored_interest.py
  test/functional/rpc_blockchain.py
  test/functional/rpc_getstoredinterest.py
Labels: kind/chore
