Repository DeFiCh/ain, pull requests merged in 2022-01, with the labels that each got.

#1010 Disable ICX - Version 2.4.0
  configure.ac
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/mn_checks.cpp
  src/rpc/blockchain.cpp
  test/functional/rpc_blockchain.py
Labels: kind/fix

#1013 Add post-FCP checkpoint
  src/chainparams.cpp
Labels: kind/chore

#1014 Bump protocol version
  src/version.h
Labels: kind/chore

#1018 Reject block that contains custom tx produced by incorrect masternode
  src/validation.cpp
Labels: kind/fix

#1017 Version 2.5.0
  configure.ac
Labels: kind/fix

#1015 @diego/v3
  configure.ac
  src/bench/checkblock.cpp
  src/bench/duplicate_inputs.cpp
  src/blockencodings.cpp
  src/blockencodings.h
  src/chain.h
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/rpc_vault.cpp
  src/miner.cpp
  src/net_processing.cpp
  src/pos.cpp
  src/pos.h
  src/primitives/block.cpp
  src/primitives/block.h
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/spv/spv_rpc.cpp
  src/test/blockencodings_tests.cpp
  src/test/pos_tests.cpp
  src/test/setup_common.cpp
  src/txdb.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/validation.h
  test/functional/feature_loan.py
  test/functional/feature_loan_basics.py
  test/functional/feature_poolswap.py
  test/functional/feature_poolswap_composite.py
  test/functional/rpc_blockchain.py
  test/functional/rpc_mn_basic.py
Labels: kind/feature

#998 Add ATTRIBUTES Gov var
  src/Makefile.am
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/gv.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  src/validation.cpp
  test/functional/feature_setgov.py
  test/functional/test_framework/test_framework.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/chore

#1027 Test liquidity rewards when poolpair status is false
  test/functional/feature_poolpair_liquidity.py
Labels: kind/feature

#1021 Add custom path option to testpoolswap RPC
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolswap_composite.py
Labels: kind/feature

#1023 Floor token swap result
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/test/liquidity_tests.cpp
  test/functional/feature_poolswap.py
Labels: kind/fix

#1032 Save attributes in view
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
Labels: kind/chore

#1033 Get attrs direct from Gov view
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/gv.cpp
  src/masternodes/gv.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
Labels: kind/chore

#1041 Fix llvm CI error
  contrib/dockerfiles/x86_64-pc-linux-gnu.dockerfile
Labels: kind/fix

#1036 Remove unused vars in mn_checks
  src/masternodes/mn_checks.cpp
Labels: kind/chore

#1037 Add option regtest to simulate mainnet target time span and spacing
  src/chainparams.cpp
  src/init.cpp
Labels: kind/feature

#956 Better define composite swap behaviour
  src/masternodes/mn_checks.cpp
  test/functional/feature_poolswap_composite.py
Labels: kind/chore

#1031 Bi-directional DEX fee burn capability
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/loan_daily_reward.cpp
  src/masternodes/govvariables/loan_liquidation_penalty.cpp
  src/masternodes/govvariables/loan_splits.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/masternodes/govvariables/lp_splits.cpp
  src/masternodes/govvariables/oracle_block_interval.cpp
  src/masternodes/govvariables/oracle_deviation.cpp
  src/masternodes/gv.cpp
  src/masternodes/gv.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_poolpair.cpp
  src/serialize.h
  src/test/liquidity_tests.cpp
  test/functional/feature_poolpair_liquidity.py
  test/functional/feature_poolswap.py
  test/functional/feature_setgov.py
Labels: kind/feature

#1035 Test hight precission calculation
  test/functional/feature_loan_low_interest.py
  test/functional/test_runner.py
Labels: kind/fix

#1034 Fix mempool reorg issue
  src/masternodes/mn_rpc.cpp
  src/rpc/blockchain.cpp
  src/txmempool.cpp
  src/txmempool.h
  test/functional/feature_restore_utxo.py
  test/functional/rpc_mn_basic.py
  test/functional/test_runner.py
Labels: kind/fix

#1043 Test whether DUSD can be used as collateral
  test/functional/feature_loan_dusd_as_collateral.py
  test/functional/test_runner.py
Labels: kind/chore

#988 Collateral increases in value and should be able to be withdrawn
  src/masternodes/mn_checks.cpp
  test/functional/feature_loan_priceupdate.py
  test/functional/feature_loan_vault.py
Labels: kind/fix

#941 Add getversioninfo
  src/clientversion.cpp
  src/clientversion.h
  src/defi-cli.cpp
  src/defi-tx.cpp
  src/defi-wallet.cpp
  src/defid.cpp
  src/init.cpp
  src/net.cpp
  src/net.h
  src/rpc/net.cpp
  src/spv/bitcoin/BRPeer.cpp
  src/spv/bitcoin/BRPeer.h
  src/test/util_tests.cpp
Labels: kind/feature

#1045 Smart contract exchange of BTC for DFI
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/balances.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_oracles.cpp
  src/rpc/util.cpp
  src/rpc/util.h
  test/functional/feature_setgov.py
  test/functional/feature_smart_contracts.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/feature

#1048 Don't count minted coins in block stats
  src/rpc/blockchain.cpp
  test/functional/feature_accounts_validation.py
Labels: kind/fix

#948 Fix pool rewards starting after actual share
  src/masternodes/poolpairs.cpp
  src/test/storage_tests.cpp
Labels: kind/fix

#1053 Fix DFI payback test
  test/functional/feature_loan_payback_dfi.py
Labels: kind/fix

#991 High precision interest calculation
  src/arith_uint256.cpp
  src/arith_uint256.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  src/test/arith_uint256_tests.cpp
  src/test/loan_tests.cpp
  src/uint256.cpp
  src/validation.cpp
  test/functional/feature_loan_low_interest.py
  test/functional/feature_loan_vault.py
  test/functional/test_runner.py
  test/lint/lint-python-dead-code-whitelist
Labels: consensus, kind/feature, area/loan

#1051 Use head commit instead of base branch merge for PR tests
  .github/workflows/tests.yaml
Labels: kind/fix

#1050 Rename vars. Update test to avoid errors.
  src/masternodes/mn_checks.cpp
  test/functional/feature_smart_contracts.py
Labels: kind/chore

#1024 Payback of DUSD loan with DFI
  src/masternodes/mn_checks.cpp
  test/functional/feature_loan_dusd_as_collateral.py
  test/functional/feature_loan_payback_dfi.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
Labels: consensus, wip, kind/feature, area/loan

#1056 Refactor gov attributes value (#1055)
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
Labels: kind/refactor

#1058 Show DEx fee percentage in pool pair JSON output
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolswap.py
Labels: kind/chore

#1057 Refactor smart contracts
  src/chainparams.cpp
  src/chainparams.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  test/functional/feature_loan_estimatecollateral.py
  test/functional/feature_loan_estimateloan.py
  test/functional/feature_loan_interest.py
  test/functional/feature_loan_vaultstate.py
  test/functional/feature_smart_contracts.py
  test/functional/rpc_listvaulthistory.py
  test/functional/rpc_mn_basic.py
Labels: kind/refactor

#1061 Resolve mempool segfault
  src/txmempool.cpp
  test/functional/feature_restore_utxo.py
Labels: kind/fix

#1063 Cleanups + indentation
  src/masternodes/masternodes.cpp
Labels: kind/chore

#1060 Accounting tokens / penalty payed via DFI
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_accounts.cpp
  test/functional/feature_loan_payback_dfi.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/feature

#1064 Revert pool find rewards changes
  src/masternodes/poolpairs.cpp
  src/test/storage_tests.cpp
Labels: kind/fix

#1065 Update test to resolve rare inconsistency
  src/txmempool.cpp
  test/functional/feature_poolswap.py
Labels: kind/bug

#1067 Fix pool swap zero amount result
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1066 Update logs and error message in mn_checks.cpp
  src/masternodes/mn_checks.cpp
  test/functional/feature_loan_vault.py
Labels: kind/chore

#1070 Fix pool rewards after actual share
  src/masternodes/poolpairs.cpp
  src/test/liquidity_tests.cpp
Labels: kind/fix

#1073 Reduce FCH migration to a single block
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  src/test/liquidity_tests.cpp
Labels: kind/fix

#1074 Tests: Replace sync_all with sync_blocks/sync_mempools
  test/functional/feature_accounts_validation.py
  test/functional/feature_anchor_rewards.py
  test/functional/feature_any_accounts_to_accounts.py
  test/functional/feature_checkpoint.py
  test/functional/feature_communitybalance_reorg.py
  test/functional/feature_initdist.py
  test/functional/feature_listaccounts_pagination.py
  test/functional/feature_loan_vault.py
  test/functional/feature_masternode_operator.py
  test/functional/feature_mempool_dakota.py
  test/functional/feature_minchainwork.py
  test/functional/feature_mine_cached.py
  test/functional/feature_oracles.py
  test/functional/feature_poolpair.py
  test/functional/feature_poolpair_liquidity.py
  test/functional/feature_poolswap.py
  test/functional/feature_rbf.py
  test/functional/feature_segwit.py
  test/functional/feature_sendtokenstoaddress.py
  test/functional/feature_tokens_basic.py
  test/functional/feature_tokens_dat.py
  test/functional/feature_update_mn.py
  test/functional/interface_rest.py
  test/functional/interface_zmq.py
  test/functional/mempool_packages.py
  test/functional/mempool_persist.py
  test/functional/mempool_reorg.py
  test/functional/p2p_segwit.py
  test/functional/p2p_segwit2.py
  test/functional/rpc_createmultisig.py
  test/functional/rpc_fundrawtransaction.py
  test/functional/rpc_getblockstats.py
  test/functional/rpc_getchaintips.py
  test/functional/rpc_getmininginfo.py
  test/functional/rpc_mn_basic.py
  test/functional/rpc_psbt.py
  test/functional/rpc_rawtransaction.py
  test/functional/rpc_signrawtransaction.py
  test/functional/rpc_txoutproof.py
  test/functional/test_framework/test_framework.py
  test/functional/wallet_address_types.py
  test/functional/wallet_avoidreuse.py
  test/functional/wallet_backup.py
  test/functional/wallet_balance.py
  test/functional/wallet_basic.py
  test/functional/wallet_bumpfee.py
  test/functional/wallet_bumpfee_totalfee_deprecation.py
  test/functional/wallet_groups.py
  test/functional/wallet_hd.py
  test/functional/wallet_import_rescan.py
  test/functional/wallet_importprunedfunds.py
  test/functional/wallet_keypool_topup.py
  test/functional/wallet_listreceivedby.py
  test/functional/wallet_listsinceblock.py
  test/functional/wallet_listtransactions.py
  test/functional/wallet_zapwallettxes.py
Labels: kind/chore

#1076 Fix format of immature interest
  src/masternodes/rpc_loan.cpp
Labels: kind/fix

#1075 Add pre and post fork loan checks
  test/functional/feature_loan_low_interest.py
Labels: kind/fix

#1077 Make burninfo API more discoverable
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#1079 Revert "Fix pool rewards after actual share (#1070)"
  src/masternodes/poolpairs.cpp
  src/test/liquidity_tests.cpp
Labels: kind/fix

#1081 Format DFI payback fee
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#1082 Higher precision interest per block info
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/rpc_loan.cpp
  src/test/loan_tests.cpp
  test/lint/lint-includes.sh
Labels: kind/fix

#1084 Test 1sat loan payback
  test/functional/feature_loan_basics.py
Labels: kind/chore

#1083 Version 2.6.0
  configure.ac
  src/chainparams.cpp
  src/version.h
Labels: kind/chore

#1085 Fix CI dirty suffix on tagged releases
  share/genbuild.sh
Labels: kind/fix

#1089 2.6.0 fixes rollup
  src/masternodes/loan.cpp
  src/masternodes/mn_checks.cpp
  src/test/amount_tests.cpp
  test/functional/rpc_getcustomtx.py
  test/functional/test_framework/messages.py
Labels: kind/fix

#1090 Version 2.6.1
  configure.ac
  share/genbuild.sh
  src/version.h
Labels: kind/fix

#1092 Test getinterest calculation
  test/functional/feature_loan_get_interest.py
  test/functional/feature_loan_payback_dfi.py
  test/functional/test_runner.py
Labels: kind/chore
