Repository DeFiCh/ain, pull requests merged in 2022-03, with the labels that each got.

#1108 Move loan and collateral token to Gov var
  src/masternodes/consensus/governance.cpp
  src/masternodes/consensus/loans.cpp
  src/masternodes/consensus/tokens.cpp
  src/masternodes/consensus/txvisitor.cpp
  src/masternodes/consensus/txvisitor.h
  src/masternodes/consensus/vaults.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/oracles.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/rpc/rawtransaction_util.cpp
  src/test/loan_tests.cpp
  src/util/strencodings.h
  src/validation.cpp
  src/validation.h
  test/functional/feature_loan_setcollateraltoken.py
  test/functional/feature_loan_vault.py
  test/functional/feature_setgov.py
  test/lint/lint-circular-dependencies.sh
  test/lint/lint-locale-dependence.sh
Labels: kind/chore

#1120 Extend lazy evaluation
  src/flushablestorage.h
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/incentivefunding.cpp
  src/masternodes/incentivefunding.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/vault.cpp
  src/masternodes/vault.h
  src/validation.cpp
Labels: kind/feature

#1054 Fix valid flag in decodecustomtx
  src/masternodes/rpc_tokens.cpp
Labels: kind/fix, 2.7.0

#1131 Remove VLA and resolve warnings in SPV
  src/spv/bitcoin/BRMerkleBlock.cpp
  src/spv/bitcoin/BRPaymentProtocol.cpp
  src/spv/bitcoin/BRPeer.cpp
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRTransaction.cpp
  src/spv/bitcoin/BRWallet.cpp
  src/spv/spv_wrapper.cpp
  src/spv/support/BRAddress.cpp
  src/spv/support/BRArray.h
  src/spv/support/BRBIP32Sequence.cpp
  src/spv/support/BRBIP39Mnemonic.cpp
  src/spv/support/BRBase58.cpp
  src/spv/support/BRBech32.cpp
  src/spv/support/BRCrypto.cpp
  src/spv/support/BRKey.cpp
  src/spv/support/BRSet.cpp
Labels: kind/chore

#1115 Use direct path in testpoolswap when available
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolswap_composite.py
Labels: kind/fix, 2.6.2

#1135 C++17
  .github/workflows/dev-builds.yaml
  build-aux/m4/ax_cxx_compile_stdcxx.m4
  ci/test/00_setup_env_mac.sh
  ci/test/05_before_script.sh
  configure.ac
  contrib/dockerfiles/x86_64-apple-darwin18.dockerfile
  depends/README.md
  depends/hosts/darwin.mk
  depends/packages/bdb.mk
  depends/packages/boost.mk
  depends/packages/native_cctools.mk
  depends/packages/zeromq.mk
  doc/dependencies.md
  make.sh
  src/span.h
Labels: kind/feature

#1136 Fix windows time
  configure.ac
  src/util/time.cpp
Labels: kind/fix

#1137 Simplify make.sh to use a single target instead of targets
  .github/workflows/dev-builds.yaml
  .github/workflows/hotfix-builds.yaml
  .github/workflows/jellyfish-tests.yml
  .github/workflows/release-builds.yaml
  make.sh
Labels: kind/refactor

#1139 Fix deadlock between blockchain and spv
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/validation.cpp
Labels: kind/fix

#1138 Version 2.6.2
  configure.ac
Labels: kind/chore

#1122 Refactor SafeAdd
  src/amount.h
  src/masternodes/consensus/accounts.cpp
  src/masternodes/incentivefunding.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/res.h
  src/masternodes/tokens.cpp
Labels: kind/refactor, 3.0.0

#1132 Cache and reuse attributes
  src/masternodes/consensus/governance.cpp
  src/masternodes/consensus/smartcontracts.cpp
  src/masternodes/consensus/vaults.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/gv.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_tokens.cpp
  src/validation.cpp
Labels: kind/refactor

#1145 Optimize allocations
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/consensus/loans.cpp
Labels: kind/chore

#1142 Introduce immutable view type
  src/flushablestorage.h
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_icxorderbook.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/rpc_vault.cpp
  src/test/storage_tests.cpp
Labels: kind/feature

#1147 Move attribute cache to dedicated rpc class
  src/masternodes/consensus/smartcontracts.cpp
  src/masternodes/consensus/vaults.cpp
  src/masternodes/gv.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_tokens.cpp
  src/serialize.h
Labels: kind/fix

#1141 Logging / spv atomic locks
  src/blockencodings.h
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/init.cpp
  src/logging.cpp
  src/logging.h
  src/masternodes/anchors.cpp
  src/masternodes/anchors.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.h
  src/masternodes/rpc_tokens.cpp
  src/masternodes/rpc_vault.cpp
  src/miner.cpp
  src/miner.h
  src/net_processing.h
  src/pos.h
  src/rest.cpp
  src/rpc/mining.cpp
  src/spv/bitcoin/BRPeer.cpp
  src/spv/bitcoin/BRPeer.h
  src/spv/bitcoin/BRPeerManager.cpp
  src/spv/bitcoin/BRWallet.cpp
  src/spv/spv_rpc.cpp
  src/spv/spv_wrapper.cpp
  src/spv/support/BRKey.cpp
  src/sync.h
  src/test/anchor_tests.cpp
  src/test/pos_tests.cpp
  src/test/sync_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/validation.h
  src/validationinterface.h
  src/wallet/ismine.cpp
  src/wallet/test/wallet_tests.cpp
  test/lint/lint-circular-dependencies.sh
Labels: kind/refactor

#1086 Add safety asserts on invalid values, full spectrum tests
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/rpc_loan.cpp
  src/test/loan_tests.cpp
Labels: kind/fix, 2.7.0

#1124 Fix number of totalAuctions in getloaninfo RPC
  src/masternodes/rpc_loan.cpp
  test/functional/feature_loan.py
Labels: kind/fix, 2.7.0

#1110 Add txn-no as a pagination token into listaccounthistory rpc
  src/masternodes/rpc_accounts.cpp
  test/functional/rpc_listaccounthistory.py
Labels: kind/feature, 2.7.0

#1128 DUSD contributes to the 50% minimum required collateral
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/mn_checks.cpp
  src/rpc/blockchain.cpp
  test/functional/feature_loan_dusd_as_collateral.py
  test/functional/rpc_blockchain.py
Labels: kind/feature, 2.7.0

#1149 Use tie for comparator
  src/masternodes/govvariables/attributes.h
  test/functional/feature_poolswap.py
Labels: kind/fix, 2.7.0

#1144 Add log category: accountchange
  src/logging.cpp
  src/logging.h
  src/masternodes/accountshistory.cpp
Labels: kind/feature

#1006 log: Adjust masternode staking output to fix issue #648
  src/logging.h
  src/miner.cpp
  src/pos.cpp
Labels: kind/fix, 2.7.0

#1143 Update boost to v1.74
  depends/packages/boost.mk
Labels: kind/fix

#1111 Generic DFI payback capability
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_loan_payback_dfi_v2.py
  test/functional/feature_loan_vault.py
  test/functional/feature_setgov.py
  test/functional/test_runner.py
Labels: consensus, kind/feature, area/loan, 2.7.0

#1153 Expand dex fee capability (#1118)
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/rpc_poolpair.cpp
  test/functional/feature_poolswap.py
  test/functional/feature_setgov.py
Labels: kind/feature

#1152 2.7.0-alpha version, protocol and FCR fork block
  configure.ac
  src/chainparams.cpp
  src/version.h
Labels: kind/chore

#1157 Fix master merge changes
  .github/workflows/release-builds.yaml
  configure.ac
  depends/packages/boost.mk
  src/Makefile.am
  src/Makefile.bench.include
  src/bench/bench_defi.cpp
  src/bench/checkblock.cpp
  src/bench/checkqueue.cpp
  src/bench/data.cpp
  src/bench/data.h
  src/bench/data/block413567.raw
  src/bench/rpc_blockchain.cpp
  src/bench/wallet_balance.cpp
  src/masternodes/accountshistory.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  src/test/loan_tests.cpp
  test/functional/feature_setgov.py
Labels: kind/fix

#1159 Fix accounting of payback burn and swap to DFI if payback token is different than native loan token or DFI.
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  test/functional/feature_loan_payback_dfi_v2.py
Labels: consensus, kind/fix, area/loan, 2.7.0

#1155 DFI2203 Futures
  src/chainparams.cpp
  src/chainparams.h
  src/logging.cpp
  src/logging.h
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/balances.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/oracles.h
  src/masternodes/res.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_oracles.cpp
  src/rpc/client.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_futures.py
  test/functional/feature_setgov.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/feature

#1161 Merge master into v3
  src/chainparams.cpp
  src/chainparams.h
  src/logging.cpp
  src/logging.h
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/consensus/loans.cpp
  src/masternodes/consensus/smartcontracts.cpp
  src/masternodes/consensus/smartcontracts.h
  src/masternodes/consensus/txvisitor.cpp
  src/masternodes/consensus/txvisitor.h
  src/masternodes/customtx.cpp
  src/masternodes/customtx.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/oracles.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_icxorderbook.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/rpc_vault.cpp
  src/rpc/client.cpp
  src/validation.cpp
  src/validation.h
  src/version.h
  test/functional/feature_futures.py
  test/functional/feature_loan_payback_dfi_v2.py
  test/functional/feature_setgov.py
  test/functional/test_runner.py
Labels: kind/fix

#1162 Vault history for new loan payback message
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1163 DFIP2203 updates
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_oracles.cpp
  src/rpc/client.cpp
  src/validation.cpp
  test/functional/feature_futures.py
Labels: kind/chore

#1165 Fix lints
  test/lint/lint-circular-dependencies.sh
Labels: kind/fix

#1167 Update dockerignore
  .dockerignore
Labels: kind/fix

#1154 Update Boost to 1.75
  depends/packages/boost.mk
Labels: kind/chore

#1168 Invert DFIP2203 token flag. Fix bug in attrs to refund disabled token.
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/validation.cpp
  test/functional/feature_futures.py
  test/functional/feature_setgov.py
Labels: kind/fix

#1171 Fix loan payback amounts
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1177 DFIP2203 minted category and txn numbering
  src/interfaces/chain.cpp
  src/interfaces/chain.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_icxorderbook.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/rpc/rawtransaction_util.cpp
  src/validation.cpp
  test/functional/feature_futures.py
Labels: kind/chore
