Repository DeFiCh/ain, pull requests merged in 2022-05, with the labels that each got.

#1217 Separate Undo and FutureSwap DB from Accounts DB
  src/Makefile.am
  src/consensus/tx_verify.cpp
  src/init.cpp
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/consensus/governance.cpp
  src/masternodes/consensus/smartcontracts.cpp
  src/masternodes/consensus/txvisitor.cpp
  src/masternodes/consensus/txvisitor.h
  src/masternodes/futureswap.cpp
  src/masternodes/futureswap.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/undo.h
  src/masternodes/undos.cpp
  src/masternodes/undos.h
  src/miner.cpp
  src/miner.h
  src/test/applytx_tests.cpp
  src/test/setup_common.cpp
  src/test/storage_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_futures.py
  test/functional/test_framework/test_framework.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/chore, 3.0.0

#1198 DFIP2203 add start block. Update FutureSwap for GW.
  src/masternodes/consensus/smartcontracts.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/masternodes.cpp
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_oracles.cpp
  src/validation.cpp
  test/functional/feature_futures.py
  test/functional/feature_setgov.py
Labels: kind/chore, 3.0.0

#1201 Calculate owner rewards for futures
  src/masternodes/consensus/smartcontracts.cpp
Labels: kind/fix, 3.0.0

#1069 Throw error on pairSymbol larger than expected
  src/masternodes/icxorder.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/rpc_vault.cpp
  src/test/blockencodings_tests.cpp
  test/functional/feature_poolpair.py
Labels: kind/fix, 3.0.0

#1146 Token split / merge
  src/consensus/tx_check.cpp
  src/consensus/tx_check.h
  src/masternodes/consensus/governance.cpp
  src/masternodes/consensus/governance.h
  src/masternodes/consensus/loans.cpp
  src/masternodes/consensus/poolpairs.cpp
  src/masternodes/consensus/tokens.cpp
  src/masternodes/customtx.cpp
  src/masternodes/customtx.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/miner.cpp
  src/test/liquidity_tests.cpp
  src/test/loan_tests.cpp
  src/test/storage_tests.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_loan_payback_dfi_v2.py
  test/functional/feature_setgov.py
  test/functional/feature_token_split.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
  test/lint/lint-locale-dependence.sh
Labels: kind/feature, 3.0.0

#1222 Fix signed overflow
  src/leveldb/db/repair.cc
  src/leveldb/db/write_batch.cc
  src/leveldb/db/write_batch_internal.h
Labels: kind/fix

#1221 fix typo and copy/paste error in documentation of withdrawfutureswap
  src/masternodes/rpc_accounts.cpp
Labels: kind/docs

#1225 Extend test and fix minor bug
  test/functional/feature_poolswap.py
Labels: kind/chore

#1228 Exclude attributes from merkle root
  src/masternodes/masternodes.cpp
Labels: kind/fix

#1233 Reject legacy anchor block not found
  src/consensus/tx_check.cpp
  src/consensus/tx_check.h
  src/validation.cpp
Labels: kind/fix

#1235 master - community balances in account change
  src/validation.cpp
Labels: kind/chore

#1234 Log community balances in account change
  src/masternodes/mn_checks.cpp
  src/validation.cpp
Labels: kind/chore

#1236 [Backport] Fix possible data race when committing block files
  src/flatfile.cpp
  src/util/system.cpp
  src/util/system.h
Labels: kind/fix, needs/kind

#1229 Move undo out of custom tx apply
  src/consensus/tx_verify.cpp
  src/init.cpp
  src/masternodes/futureswap.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_tokens.cpp
  src/masternodes/undo.h
  src/masternodes/undos.cpp
  src/masternodes/undos.h
  src/miner.cpp
  src/miner.h
  src/test/applytx_tests.cpp
  src/test/storage_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
Labels: kind/refactor

#1227 Token split refund balance on error
  src/validation.cpp
Labels: kind/chore

#1239 test: Prevent wallet resubmitting TX after rollback
  test/functional/feature_loan_payback_dfi_v2.py
Labels: kind/fix

#1241 Only set auto lock on loan token
  src/masternodes/govvariables/attributes.cpp
  test/functional/feature_setgov.py
Labels: kind/fix

#1237 Refactor community balance logs
  src/masternodes/mn_checks.cpp
  src/validation.cpp
Labels: kind/chore

#1244 Bring back undo in merkle root
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/miner.cpp
  src/validation.cpp
Labels: kind/fix

#1245 Test Gov var by height cumulatively against all other stored Gov vars
  src/masternodes/consensus/governance.cpp
  src/masternodes/gv.cpp
  src/masternodes/gv.h
  src/validation.cpp
  test/functional/feature_setgov.py
Labels: kind/bug

#934 Restore updatemasternode and combine setforcedrewardaddress / removeforcedaddress
  src/consensus/tx_verify.cpp
  src/masternodes/anchors.cpp
  src/masternodes/consensus/masternodes.cpp
  src/masternodes/consensus/masternodes.h
  src/masternodes/consensus/proposals.cpp
  src/masternodes/customtx.cpp
  src/masternodes/customtx.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_proposals.cpp
  src/miner.cpp
  src/pos.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/test/applytx_tests.cpp
  src/test/blockencodings_tests.cpp
  src/test/pos_tests.cpp
  src/test/setup_common.cpp
  src/txdb.cpp
  src/validation.cpp
  test/functional/feature_update_mn.py
  test/functional/rpc_getcustomtx.py
  test/functional/rpc_updatemasternode.py
  test/functional/test_runner.py
Labels: kind/feature, 3.0.0

#1240 Context for proposals
  src/masternodes/consensus/proposals.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_proposals.cpp
  src/rpc/client.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/feature, area/governance, 3.0.0

#1220 Consortium members attribute for minting DAT tokens
  configure.ac
  src/masternodes/consensus/tokens.cpp
  src/masternodes/consensus/tokens.h
  src/masternodes/consensus/txvisitor.cpp
  src/masternodes/customtx.cpp
  src/masternodes/customtx.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/tokens.h
  src/rpc/client.cpp
  src/test/applytx_tests.cpp
  src/test/storage_tests.cpp
  test/functional/feature_consortium.py
  test/functional/feature_setgov.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
Labels: consensus, kind/feature, area/governance, area/tokens, 3.0.0

#1119 Unset governance variable
  src/masternodes/consensus/governance.cpp
  src/masternodes/consensus/governance.h
  src/masternodes/customtx.cpp
  src/masternodes/customtx.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/icx_takerfee_per_btc.h
  src/masternodes/govvariables/loan_daily_reward.cpp
  src/masternodes/govvariables/loan_daily_reward.h
  src/masternodes/govvariables/loan_liquidation_penalty.cpp
  src/masternodes/govvariables/loan_liquidation_penalty.h
  src/masternodes/govvariables/loan_splits.cpp
  src/masternodes/govvariables/loan_splits.h
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.h
  src/masternodes/govvariables/lp_splits.cpp
  src/masternodes/govvariables/lp_splits.h
  src/masternodes/govvariables/oracle_block_interval.cpp
  src/masternodes/govvariables/oracle_block_interval.h
  src/masternodes/govvariables/oracle_deviation.cpp
  src/masternodes/govvariables/oracle_deviation.h
  src/masternodes/gv.cpp
  src/masternodes/gv.h
  src/masternodes/icxorder.cpp
  src/masternodes/icxorder.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/oracles.cpp
  src/masternodes/oracles.h
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/rpc_customtx.cpp
  src/rpc/client.cpp
  test/functional/feature_setgov.py
Labels: kind/feature, 3.0.0

#1248 Fix conflicting tx message char and few more issues
  src/masternodes/consensus/masternodes.cpp
  src/masternodes/consensus/tokens.cpp
  src/masternodes/consensus/txvisitor.cpp
  src/masternodes/consensus/txvisitor.h
  src/masternodes/customtx.h
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
Labels: kind/fix, 3.0.0

#1250 Move consortium to separate key in attributes instead under token key.
  src/masternodes/consensus/tokens.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/rpc_tokens.cpp
  test/functional/feature_consortium.py
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_loan_payback_dfi_v2.py
  test/functional/feature_setgov.py
Labels: consensus, kind/refactor, area/governance, 3.0.0

#1253 Fix issue with Gov var height
  configure.ac
  src/validation.cpp
Labels: kind/bug

#994 Custom transaction version and expiration
  src/consensus/tx_check.cpp
  src/consensus/tx_check.h
  src/init.cpp
  src/masternodes/customtx.cpp
  src/masternodes/customtx.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_poolpair.cpp
  src/primitives/transaction.h
  src/rpc/client.cpp
  src/test/util_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  test/functional/feature_anchor_rewards.py
  test/functional/feature_reject_customtxs.py
  test/functional/feature_tx_versioning_and_expiration.py
  test/functional/test_runner.py
Labels: kind/feature, 3.0.0

#1255 Use no throw function to get value
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/loan_daily_reward.cpp
  src/masternodes/govvariables/loan_liquidation_penalty.cpp
  src/masternodes/govvariables/loan_splits.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/masternodes/govvariables/lp_splits.cpp
  src/masternodes/govvariables/oracle_deviation.cpp
  test/functional/feature_setgov.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/bug

#1247 Token split support multiple pool and pool created in the block.
  src/miner.cpp
  src/validation.cpp
  src/validation.h
Labels: kind/bug

#1256 Migrate all keys on token split
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/validation.cpp
  test/functional/feature_token_split.py
Labels: kind/bug

#970 Introduce new CRPCStats class to save key RPC statistics
  src/Makefile.am
  src/httprpc.cpp
  src/init.cpp
  src/rpc/register.h
  src/rpc/stats.cpp
  src/rpc/stats.h
  test/functional/feature_rpcstats.py
  test/functional/rpc_help.py
  test/functional/test_runner.py
  test/lint/check-rpc-mappings.py
  test/lint/lint-includes.sh
Labels: kind/feature, 3.0.1

#1258 Fix creategovvoc argument parsing
  src/masternodes/rpc_proposals.cpp
  src/rpc/client.cpp
Labels: kind/fix

#1260 Backport RPCStats to master
  src/Makefile.am
  src/httprpc.cpp
  src/init.cpp
  src/rpc/register.h
  src/rpc/stats.cpp
  src/rpc/stats.h
  test/functional/feature_rpcstats.py
  test/functional/rpc_help.py
  test/functional/test_runner.py
  test/lint/check-rpc-mappings.py
  test/lint/lint-includes.sh
Labels: kind/chore

#1243 Token splits, token lock and move loan and collateral token to Gov vars
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/tx_check.cpp
  src/consensus/tx_check.h
  src/init.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/gv.h
  src/masternodes/loan.cpp
  src/masternodes/loan.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/oracles.cpp
  src/masternodes/oracles.h
  src/masternodes/poolpairs.cpp
  src/masternodes/poolpairs.h
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/miner.cpp
  src/rpc/blockchain.cpp
  src/util/strencodings.h
  src/validation.cpp
  src/validation.h
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_loan_payback_dfi_v2.py
  test/functional/feature_loan_setcollateraltoken.py
  test/functional/feature_loan_vault.py
  test/functional/feature_setgov.py
  test/functional/feature_token_lock.py
  test/functional/feature_token_split.py
  test/functional/rpc_blockchain.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
  test/lint/lint-locale-dependence.sh
Labels: kind/feature, 2.8.0

#1263 Use previous height when setting interest
  src/validation.cpp
Labels: kind/fix

#1261 Add interrupt-block, stop-block, refactor stats, explicit validity checks
  .gitignore
  src/init.cpp
  src/masternodes/mn_checks.cpp
  src/rpc/stats.cpp
  src/rpc/stats.h
  src/validation.cpp
  src/validation.h
  test/lint/check-doc.py
Labels: kind/feature

#1262 Add filtering mechanism for listgovs
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_rpc.cpp
  test/functional/feature_setgov.py
Labels: kind/feature

#1264 2.8.0
  configure.ac
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/tokens.cpp
  src/miner.cpp
  src/rpc/blockchain.cpp
  src/validation.cpp
  src/version.h
  test/functional/feature_loan_vault.py
  test/functional/feature_setgov.py
  test/functional/feature_token_lock.py
  test/functional/feature_token_split.py
  test/functional/rpc_blockchain.py
Labels: kind/chore, 2.8.0

#1265 Update token related calls for Fort Canning Crunch
  src/masternodes/mn_checks.cpp
  test/functional/feature_loan_setcollateraltoken.py
  test/functional/feature_loan_setloantoken.py
  test/functional/feature_loan_vault.py
Labels: kind/feature

#1267 Rename fortcanningspicegarden to fortcanningcrunch
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/tx_check.cpp
  src/consensus/tx_check.h
  src/init.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/tokens.cpp
  src/miner.cpp
  src/rpc/blockchain.cpp
  src/validation.cpp
  test/functional/feature_loan_setcollateraltoken.py
  test/functional/feature_loan_setloantoken.py
  test/functional/feature_loan_vault.py
  test/functional/feature_setgov.py
  test/functional/feature_token_lock.py
  test/functional/feature_token_split.py
  test/functional/rpc_blockchain.py
Labels: kind/fix, 2.8.0

#1266 Fix pool name bugs
  src/masternodes/mn_checks.cpp
  src/miner.cpp
  src/validation.cpp
Labels: kind/fix

#1268 Restore validation to setloantoken
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/loan.cpp
  src/masternodes/mn_checks.cpp
  test/functional/feature_loan_setloantoken.py
Labels: kind/chore

#1270 Search all pools for previous version suffix
  src/validation.cpp
Labels: kind/fix

#1272 Restore updateloantoken
  src/masternodes/loan.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_loan.cpp
  test/functional/feature_loan_setloantoken.py
  test/functional/feature_loan_vault.py
Labels: kind/feature

#1276 Correct no loan scheme typo
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1274 Remove comma from splits
  src/masternodes/govvariables/attributes.cpp
  test/functional/feature_setgov.py
  test/functional/feature_token_split.py
Labels: kind/chore

#1273 Add mocknet helpers
  .gitignore
  contrib/devtools/mocknet.patch
  src/chainparams.cpp
  src/chainparams.h
  src/init.cpp
  test/lint/check-doc.py
Labels: kind/feature

#1280 Fix precision for CAmount in attributes
  src/masternodes/govvariables/attributes.cpp
  test/functional/feature_loan_setcollateraltoken.py
  test/functional/feature_loan_setloantoken.py
Labels: kind/bug

#1271 Add legacy filtering mode
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_rpc.cpp
  test/functional/feature_setgov.py
  test/functional/feature_token_split.py
Labels: kind/feature, 2.8.0

#1283 Fix collateral test
  test/functional/feature_loan_setcollateraltoken.py
Labels: kind/bug

#1286 Fix mocknet activation params
  src/chainparams.cpp
  src/init.cpp
Labels: kind/fix

#1285 Better logging for token splits
  src/validation.cpp
Labels: kind/fix

#1287 Fix removal of last liquidity on empty used pool
  src/validation.cpp
  src/validation.h
Labels: kind/fix

#1290 Refund future swaps on split
  src/masternodes/accounts.h
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_accounts.cpp
  src/validation.cpp
  test/functional/feature_token_split.py
Labels: kind/fix

#1293 Fix for future swap owner rewards calc
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1295 Allow only one token split per block and reject token split on same block as setgov
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/gv.cpp
  src/masternodes/gv.h
  src/masternodes/mn_checks.cpp
  src/validation.cpp
  test/functional/feature_setgov.py
  test/functional/feature_token_split.py
Labels: kind/fix, area/governance, 2.8.0

#1292 Refactor mocknet and add more params
  src/chainparams.cpp
  src/chainparams.h
Labels: kind/feature

#1296 Scale auction bid and batches for split
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/rpc_vault.cpp
  src/masternodes/vault.cpp
  src/masternodes/vault.h
  src/masternodes/vaulthistory.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_token_split.py
Labels: kind/fix

#1291 Add concurrency for reward calculation to scale out
  src/logging.cpp
  src/logging.h
  src/validation.cpp
  test/lint/lint-includes.sh
Labels: kind/fix

#1284 Tests for token splits
  test/functional/feature_token_split.py
  test/functional/feature_token_split_mechanism.py
  test/functional/feature_token_split_usd_value.py
  test/functional/test_runner.py
Labels: kind/fix, 2.8.0

#1299 Check collateral for migrating token
  src/validation.cpp
  test/functional/feature_token_split.py
Labels: kind/fix

#1297 Fix conventions and usd tests
  test/functional/feature_token_split_usd_value.py
Labels: kind/fix

#1300 Finishing touches
  src/validation.cpp
Labels: kind/fix, 2.8.0

#1303 Add collateral test
  test/functional/feature_token_split.py
Labels: kind/chore

#1302 Test vault usd value split
  test/functional/feature_token_split_usd_value.py
Labels: kind/fix

#1307 Uses sysctl -n hw.logicalcpu instead of nproc on macOS
  make.sh
Labels: kind/fix

#1309 Reenable the option to disable checkpoints
  src/chainparams.cpp
  src/chainparams.h
  src/init.cpp
  src/validation.h
Labels: kind/feature

#1310 Log fd limits, minor cleanup
  src/scheduler.cpp
  src/util/system.cpp
  src/util/threadnames.cpp
Labels: kind/chore

#1311 Return -1 value on getvault when tokens are locked
  src/masternodes/rpc_vault.cpp
  test/functional/feature_token_lock.py
  test/functional/feature_token_split_usd_value.py
Labels: kind/fix

#1312 Verbose flag to getvault to get nextCollateralRatio
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan_priceupdate.py
Labels: kind/feature

#1314 Interest per block value and amounts on getvault
  src/masternodes/rpc_vault.cpp
  test/functional/feature_loan_priceupdate.py
  test/functional/feature_token_lock.py
Labels: kind/feature

#1313 Support of consolidating rewards on start
  src/init.cpp
  src/validation.cpp
  src/validation.h
Labels: kind/feature

#1316 Add revert for PaybackV2
  src/masternodes/mn_checks.cpp
Labels: kind/fix, area/loan

#1317 Version 2.8.1-rc
  configure.ac
Labels: kind/chore
