Repository DeFiCh/ain, pull requests merged in 2022-09, with the labels that each got.

#1439 Add Great World alias
  src/chainparams.cpp
  src/init.cpp
Labels: kind/chore

#1436 Allow negative interest value
  src/masternodes/rpc_vault.cpp
  test/functional/feature_negative_interest.py
  test/functional/feature_stored_interest.py
Labels: kind/fix

#1449 Add FortCanningEpilogue fork
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/rpc/blockchain.cpp
  test/functional/rpc_blockchain.py
Labels: kind/feature

#1447 Fix payback to account for negative interest
  src/masternodes/mn_checks.cpp
  test/functional/feature_negative_interest.py
  test/functional/feature_negative_loan_interest.py
Labels: consensus, kind/fix, area/loan

#1438 Change deprecated functions
  src/key.cpp
  src/spv/support/BRKey.cpp
Labels: kind/chore

#1453 Run full sync on PR labels `consensus` or `ci/sync`
  .github/workflows/fullsync-tests.yml
Labels: kind/fix, test/sync

#1452 Allow higher collateral factor
  src/amount.h
  src/masternodes/govvariables/attributes.cpp
  src/test/setup_common.h
  test/functional/feature_higher_collateral_factor.py
  test/functional/feature_setgov.py
  test/functional/test_runner.py
Labels: kind/feature, ci/sync, v/2.11.0

#1444 Track Negative Interest
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/validation.cpp
  src/validation.h
  test/functional/feature_negative_loan_interest.py
  test/functional/feature_stored_interest.py
Labels: kind/chore

#1451 Allow payback of DUSD with vault's collateral
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/loan.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_loan.cpp
  test/functional/feature_loan_payback_with_collateral.py
  test/functional/feature_setgov.py
  test/functional/test_runner.py
Labels: kind/feature, v/2.11.0

#1456 Add negativeinterest to SET_DOC_OPTIONAL
  test/lint/check-doc.py
Labels: kind/fix

#1457 Fix full sync not being initialized when PR updates ci/label
  .github/workflows/fullsync-tests.yml
Labels: kind/fix

#1450 Update DFI DUSD vault collateral requirement rules
  src/masternodes/mn_checks.cpp
  test/functional/feature_dusd_loans.py
  test/functional/feature_loan_dusd_as_collateral.py
  test/functional/rpc_getstoredinterest.py
  test/functional/test_runner.py
Labels: kind/feature, ci/sync, v/2.11.0

#1458 Set testnet fork on 1244000
  src/chainparams.cpp
Labels: kind/chore

#1460 Fix loan tests
  test/functional/feature_loan_vault.py
  test/functional/feature_negative_loan_interest.py
Labels: kind/fix

#1463 More test fixes
  test/functional/feature_higher_collateral_factor.py
  test/functional/feature_loan_priceupdate.py
  test/functional/feature_negative_interest.py
Labels: kind/fix

#1461 v2.11
  configure.ac
Labels: kind/chore

#1472 Fall back to 100% if there are no loan schemes
  src/masternodes/govvariables/attributes.cpp
Labels: kind/fix

#1467 ICX token type fix and enable on testnet
  src/masternodes/mn_checks.cpp
  test/functional/feature_icx_orderbook.py
Labels: kind/fix

#1471 Jellyfish CI fails on error
  .github/workflows/jellyfish-tests.yml
Labels: kind/fix

#1474 Set Epilogue hard fork
  configure.ac
  src/chainparams.cpp
Labels: kind/chore

#1437 Add RPC updatemasternode call
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/masternodes/anchors.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/pos.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/test/blockencodings_tests.cpp
  src/test/pos_tests.cpp
  src/test/setup_common.cpp
  src/txdb.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/validation.h
  test/functional/feature_accounts_n_utxos.py
  test/functional/feature_update_mn.py
  test/functional/rpc_getcustomtx.py
  test/functional/rpc_updatemasternode.py
  test/functional/test_runner.py
Labels: kind/feature

#1477 Guard ICX fix for testnet
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1478 v2.11.1
  configure.ac
Labels: kind/chore

#1479 Allow ICX fix on RegTest
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1441 On-chain governance
  src/Makefile.am
  src/chainparams.cpp
  src/consensus/params.h
  src/masternodes/communityaccounttypes.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/incentivefunding.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/proposals.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_proposals.cpp
  src/miner.cpp
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/register.h
  src/validation.cpp
  src/validation.h
  test/functional/feature_community_development_funds.py
  test/functional/feature_loan_payback_dfi.py
  test/functional/feature_loan_payback_dfi_v2.py
  test/functional/feature_on_chain_government.py
  test/functional/feature_setgov.py
  test/functional/rpc_help.py
  test/functional/test_runner.py
  test/lint/check-rpc-mappings.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/feature, area/governance, v/3.0.0

#1489 Track negative interest in collateral payback
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1495 Fix payback/empty swap from genesis and force reindex
  src/init.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  test/functional/feature_poolswap.py
Labels: kind/fix, ci/sync

#1492 After GC make foundation reward as token when on-chain governance is disabled
  src/validation.cpp
  src/validation.h
  test/functional/feature_community_development_funds.py
  test/functional/feature_on_chain_government.py
Labels: consensus, kind/feature, area/governance, v/3.0.0
