Repository DeFiCh/ain, pull requests merged in 2023-02, with the labels that each got.

#1716 Remove codowners to manually add reviewers
  .github/CODEOWNERS
Labels: kind/chore

#1705 Add lambda support to Require
  src/amount.h
  src/masternodes/res.h
Labels: kind/fix

#1709 Disable neutral votes from RPC
  src/init.cpp
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_fee_distribution.py
Labels: kind/fix, v/3.2.3

#1727 Fix on-chain goverment voting scenarios test
  test/functional/feature_on_chain_government_voting_scenarios.py
Labels: kind/chore

#1719 Fix setgov crashes
  src/masternodes/mn_rpc.cpp
Labels: kind/fix, v/3.2.3

#1731 Version 3.2.3
  configure.ac
Labels: kind/chore

#1700 Move CHistoryWriter into CCustomCSView
  src/Makefile.am
  src/consensus/tx_verify.cpp
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/historywriter.cpp
  src/masternodes/historywriter.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/rpc_tokens.cpp
  src/masternodes/validation.cpp
  src/validation.cpp
  test/lint/lint-circular-dependencies.sh
Labels: kind/fix, v/3.2.4

#1715 Track Add/SubVaultCollateral in vault history
  src/masternodes/accountshistory.cpp
  src/masternodes/accountshistory.h
  src/masternodes/rpc_vault.cpp
  src/masternodes/vault.h
  src/masternodes/vaulthistory.h
  test/functional/rpc_listvaulthistory.py
Labels: kind/fix, v/3.2.4

#1729 Add more voting info in getgovproposal rpc
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/feature, area/governance, v/3.2.4

#1732 Change first parameter of listgovproposals and listgovproposalvotes to be string and parsed as JSON in rpc
  src/masternodes/rpc_proposals.cpp
  src/rpc/client.cpp
Labels: kind/fix, area/governance, v/3.2.4

#1717 rpc: votegov: Add support for owner and operator address
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government_voting_scenarios.py
Labels: kind/feature, v/3.2.4

#1728 Addapt fee redistribution test to current situation
  test/functional/feature_on_chain_government_fee_distribution.py
Labels: kind/chore, area/governance

#1712 Remove positive amount on close vault
  src/init.cpp
  src/masternodes/mn_checks.cpp
Labels: kind/fix, v/3.2.4

#1725 Display vote validity in `listgovproposals` and add validity filter
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_voting_scenarios.py
Labels: kind/feature, area/governance, v/3.2.4

#1714 Display aggregate vote stats in `listgovproposalvotes`
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_voting_scenarios.py
Labels: kind/feature, v/3.2.4

#1738 Add checkpoints to testnet/devnet
  src/chainparams.cpp
Labels: kind/fix, v/3.2.4

#1742 Fix getcustomtx crash on mempool transaction
  src/masternodes/rpc_customtx.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/fix, v/3.2.4

#1740 Display vote validity in listgovproposals and add validity filter
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/feature, v/3.2.4

#1741 Fix staker crash on invalidateblock
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/rpc_masternodes.cpp
  src/miner.cpp
  src/pos.cpp
  src/rpc/mining.cpp
Labels: kind/fix, v/3.2.4

#1745 v3.2.4
  configure.ac
Labels: kind/chore, v/3.2.4

#1744 Resolve functional test failure
  test/functional/feature_on_chain_government_fee_distribution.py
Labels: kind/fix

#1749 Allow object to be empty in listgovproposals and listgovproposalvotes
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
  test/functional/rpc_listgovproposals.py
  test/functional/test_framework/test_framework.py
Labels: kind/fix

#1754 Add auto transaction ordering support
  src/init.cpp
  src/miner.cpp
  src/policy/fees.cpp
  src/rpc/mining.cpp
  src/validation.h
Labels: kind/feature

#1755 Replace Require strings with lambdas
  src/amount.h
  src/chainparams.cpp
  src/masternodes/accounts.cpp
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/loan_daily_reward.cpp
  src/masternodes/govvariables/loan_liquidation_penalty.cpp
  src/masternodes/govvariables/loan_splits.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/masternodes/govvariables/lp_splits.cpp
  src/masternodes/govvariables/oracle_block_interval.cpp
  src/masternodes/govvariables/oracle_deviation.cpp
  src/masternodes/gv.cpp
  src/masternodes/incentivefunding.cpp
  src/masternodes/loan.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/oracles.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/tokens.cpp
  src/masternodes/validation.cpp
  src/masternodes/vault.cpp
  src/rpc/rawtransaction_util.cpp
Labels: kind/fix, v/3.2.5

#1757 Use if conditionals in amount
  src/amount.h
  src/masternodes/accounts.cpp
Labels: kind/fix

#1759 Add `-txordering` flag: support for miners to switch TX ordering
  src/init.cpp
  src/miner.cpp
  src/policy/fees.cpp
  src/rpc/mining.cpp
  src/validation.h
Labels: kind/feature, v/3.2.5

#1762 Multi-threaded getburninfo
  src/masternodes/rpc_accounts.cpp
  src/masternodes/validation.h
Labels: kind/chore

#1761 Refactor `-txordering` to remove multiple GetArg calls
  src/init.cpp
  src/miner.cpp
  src/miner.h
  src/policy/fees.cpp
  src/rpc/mining.cpp
  src/validation.h
  test/lint/lint-circular-dependencies.sh
Labels: kind/refactor

#1758 Add DeFiErrors abstraction for error messages
  src/Makefile.am
  src/masternodes/errors.h
  src/masternodes/mn_checks.cpp
Labels: kind/refactor

#1718 Do not allow non-DAT consortium attributes to be set
  src/masternodes/mn_rpc.cpp
  test/functional/feature_consortium.py
Labels: kind/fix

#1752 Disconnect nodes in rollback_to
  test/functional/feature_loan_payback_with_collateral.py
  test/functional/feature_negative_interest.py
  test/functional/feature_on_chain_government_fee_distribution.py
  test/functional/feature_on_chain_government_govvar_update.py
  test/functional/feature_poolswap.py
  test/functional/feature_restore_utxo.py
  test/functional/rpc_getstoredinterest.py
  test/functional/test_framework/test_framework.py
Labels: kind/chore

#1769 Revert Require to simple if branches on payback hotpaths
  src/masternodes/errors.h
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1768 Revert to if conditional for Add/Sub
  src/masternodes/accounts.cpp
Labels: kind/chore

#1765 Remove usage of ForEachAccount
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/rpc_accounts.cpp
  test/functional/feature_on_chain_government_fee_distribution.py
Labels: kind/fix

#1723 Add rollback diff to full sync CI
  .github/workflows/fullsync-tests.yml
  ci/parallel_sync/sync.sh
Labels: kind/feature

#1770 Add checkpoint for maintest and testnest
  src/chainparams.cpp
Labels: kind/chore

#1764 Limit parallel script processing thread pool to 4 by default
  src/init.cpp
Labels: kind/chore

#1773 Add thread pool to improve performance of multi-threading
  src/Makefile.am
  src/init.cpp
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/threadpool.cpp
  src/masternodes/threadpool.h
  src/masternodes/validation.h
Labels: kind/chore

#1772 Bump jellyfish-workflow settings
  .github/workflows/jellyfish-tests.yml
Labels: kind/chore

#1753 Version 3.2.5
  configure.ac
Labels: kind/chore, v/3.2.5

#1774 Reverts of Require in Sub/Add Balances
  src/masternodes/balances.h
Labels: kind/chore

#1781 Add more consistent checkpoints
  src/chainparams.cpp
Labels: kind/chore

#1779 tests: mint multiple tokens to an address
  test/functional/feature_consortium.py
Labels: kind/chore

#1780 gettokenbalances should only return spendable amounts
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#1711 Change proposal approval threshold
  src/masternodes/validation.cpp
  test/functional/feature_on_chain_government_voting_scenarios.py
Labels: kind/fix, area/governance

#1782 Version 3.2.6
  configure.ac
Labels: kind/chore
