Repository DeFiCh/ain, pull requests merged in 2023-03, with the labels that each got.

#1785 Update listtransactions help dialogue
  src/wallet/rpcwallet.cpp
Labels: kind/docs

#1791 Cache getblockchaininfo result
  src/rpc/blockchain.cpp
Labels: kind/feature

#1788 rpc: getburninfo performance improvements
  src/init.cpp
  src/masternodes/rpc_accounts.cpp
  src/rpc/resultcache.cpp
  src/rpc/resultcache.h
  test/functional/feature_consortium.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/fix, v/3.2.7

#1793 Remove int type warning
  src/masternodes/rpc_accounts.cpp
Labels: kind/chore

#1766 Add missing CalculateOwnerRewards calls
  src/masternodes/mn_checks.cpp
  src/masternodes/validation.cpp
Labels: kind/fix, v/3.2.7

#1789 Restore ForEachAccount
  src/masternodes/accounts.cpp
  src/masternodes/accounts.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix, v/3.2.7

#1796 Fix getburninfo memoization
  src/masternodes/rpc_accounts.cpp
Labels: kind/fix

#1797 Fix CLockFreeGuard, introduce AtomicMutex
  src/sync.h
Labels: kind/fix

#1799 Switch getburninfo to use BufferPool
  src/masternodes/rpc_accounts.cpp
  src/sync.h
Labels: kind/chore

#1802 Track reward addresses in settings
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
Labels: kind/fix

#1800 Eliminate the use of CLockFreeGuard with AtomicMutex
  src/miner.cpp
  src/miner.h
  src/rpc/mining.cpp
  src/rpc/resultcache.cpp
  src/rpc/resultcache.h
  src/rpc/stats.cpp
  src/rpc/stats.h
  src/sync.h
  src/test/sync_tests.cpp
  src/wallet/ismine.cpp
Labels: kind/fix

#1713 Test framework: Initial impl of exhaustive state verification with rollback
  test/functional/feature_framework_rollback.py
  test/functional/test_framework/test_framework.py
  test/functional/test_runner.py
Labels: kind/fix, v/3.2.7

#1803 Add concurrency to liquidated vault validation
  ci/parallel_sync/sync.sh
  src/masternodes/validation.cpp
Labels: kind/feature

#1804 Abstract errors
  src/Makefile.am
  src/masternodes/errors.h
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
Labels: kind/chore

#1806 Add lock before vault liquidation
  src/masternodes/validation.cpp
Labels: kind/fix

#1790 Version 3.2.7
  configure.ac
Labels: kind/chore

#1808 Add RPC metadata capability and coin selection options
  src/Makefile.am
  src/defi-cli.cpp
  src/httprpc.cpp
  src/masternodes/coinselect.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/mn_rpc.h
  src/masternodes/rpc_proposals.cpp
  src/rpc/request.h
  src/util/system.h
  src/wallet/rpcwallet.cpp
  src/wallet/rpcwallet.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: kind/feature

#1493 Cleanup Github labels, bots, review
  .github/CODEOWNERS
  .github/governance.yml
  .github/labels.yml
Labels: kind/refactor

#1812 Fix GetDecimalString typo
  src/amount.h
  src/masternodes/errors.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/loan.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_vault.cpp
  src/test/amount_tests.cpp
Labels: v/next-release

#1811 Rename CLoanCollaterals to CVaultAssets
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_vault.cpp
  src/masternodes/validation.cpp
  src/masternodes/validation.h
  src/masternodes/vaulthistory.cpp
  src/masternodes/vaulthistory.h
  src/test/loan_tests.cpp
Labels: v/next-release

#1814 In CreateTransaction pass coinSelectOpts to AvailableCoin. Remove dead code.
  src/masternodes/mn_rpc.cpp
  src/masternodes/rpc_proposals.cpp
  src/wallet/wallet.cpp
Labels: v/next-release

#1819 Remove `Require` from governance attributes
  src/masternodes/errors.h
  src/masternodes/govvariables/attributes.cpp
Labels: v/next-release

#1818 net: rate limit the processing of incoming addr messages
  src/init.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/net_processing.h
  src/rpc/net.cpp
  src/util/system.cpp
  src/util/system.h
  test/lint/lint-locale-dependence.sh
Labels: v/next-release

#1822 Replace more require usages
  src/amount.h
  src/masternodes/accounts.cpp
  src/masternodes/errors.h
  src/masternodes/gv.cpp
  src/masternodes/icxorder.cpp
  test/lint/lint-circular-dependencies.sh
Labels: v/next-release

#1820 Adds coin select flags to defid with option to override from CLI
  src/Makefile.am
  src/init.cpp
  src/masternodes/coinselect.h
  src/masternodes/mn_rpc.cpp
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_icxorderbook.cpp
  src/masternodes/rpc_loan.cpp
  src/masternodes/rpc_masternodes.cpp
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/rpc_proposals.cpp
  src/masternodes/rpc_tokens.cpp
  src/masternodes/rpc_vault.cpp
  src/rpc/request.h
  src/util/system.cpp
  src/util/system.h
  src/wallet/wallet.cpp
Labels: v/next-release

#1810 Add sleep in batchvote rpc
  src/init.cpp
  src/masternodes/rpc_proposals.cpp
Labels: v/next-release

#1832 WIP: Add HD Wallet Ethereum address support
  src/Makefile.am
  src/chainparams.h
  src/crypto/sha3.cpp
  src/crypto/sha3.h
  src/hash.h
  src/key.cpp
  src/key.h
  src/key_io.cpp
  src/outputtype.cpp
  src/outputtype.h
  src/pubkey.h
  src/rpc/util.cpp
  src/script/interpreter.h
  src/script/signingprovider.cpp
  src/script/signingprovider.h
  src/script/standard.cpp
  src/script/standard.h
  src/test/transaction_tests.cpp
  src/wallet/ismine.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/wallet_hd.py
Labels: evm

#1841 Add import/export for Eth addresses. Make Eth solvable.
  src/init.cpp
  src/key_io.cpp
  src/outputtype.cpp
  src/pubkey.h
  src/script/interpreter.cpp
  src/script/interpreter.h
  src/script/script.cpp
  src/script/script.h
  src/script/sign.cpp
  src/script/signingprovider.cpp
  src/script/standard.cpp
  src/wallet/rpcdump.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/wallet_hd.py
Labels: evm

#1839 Block TXs to EVM addresses
  src/policy/policy.cpp
  src/validation.cpp
  test/functional/wallet_hd.py
Labels: evm

#1846 Consolidates to single generated header and staticlib
  src/Makefile.am
  src/defid.cpp
  src/rpc/libain_wrapper.cpp
  src/rpc/libain_wrapper.h
  src/rust/Cargo.lock
  src/rust/Cargo.toml
  src/rust/Makefile
  src/rust/crates/ain-evm-ffi/Cargo.toml
  src/rust/crates/ain-evm-ffi/build.rs
  src/rust/crates/ain-evm-ffi/src/lib.rs
  src/rust/crates/ain-evm/Cargo.toml
  src/rust/crates/ain-evm/src/lib.rs
  src/rust/crates/ain-grpc/Cargo.toml
  src/rust/crates/ain-grpc/build.rs
  src/rust/crates/ain-grpc/src/lib.rs
Labels: evm
