Repository DeFiCh/ain, pull requests merged in 2023-09, with the labels that each got.

#2390 evm: Add next block baseFeePerGas in `eth_feeHistory` output
  lib/ain-evm/src/block.rs
  lib/ain-grpc/src/block.rs
  test/functional/feature_evm_rpc_fee_history.py
Labels: v/next-release

#2332 Add consensus check on transferdomain accounting
  lib/ain-evm/src/backend.rs
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/evm.rs
  lib/ain-rs-exports/src/evm.rs
  lib/ain-rs-exports/src/lib.rs
  src/masternodes/errors.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/attributes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/validation.cpp
  src/masternodes/validation.h
  src/validation.cpp
  test/functional/feature_evm.py
  test/functional/feature_evm_transferdomain.py
Labels: v/next-release, evm

#2407 Remove EVM block size check in validation
  src/validation.cpp
Labels: protocol

#2369 Fix witness v16 endianness
  src/hash.h
  src/key_io.cpp
  src/masternodes/consensus/xvm.cpp
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_evm.cpp
  src/miner.cpp
  src/script/standard.cpp
  src/script/standard.h
  src/test/key_tests.cpp
Labels: protocol, v/next-release

#2389 evm: Move DFIIntrinsics contract, reserve space for additional contracts
  lib/ain-contracts/src/lib.rs
  lib/ain-evm/src/contract.rs
  lib/ain-evm/src/evm.rs
  test/functional/feature_evm_dfi_intrinsics.py
Labels: protocol, v/next-release

#2380 evm: Add tests related to contracts size
  test/functional/feature_evm_contract_env_vars.py
  test/functional/feature_evm_contracts.py
  test/functional/feature_evm_logs.py
  test/functional/feature_evm_miner.py
  test/functional/test_framework/evm_contract.py
  test/functional/test_framework/util.py
Labels: v/next-release

#2375 evm: Enable DST20 optimisation
  lib/ain-contracts/build.rs
Labels: protocol, v/next-release

#2396 evm: Add tests for proxy
  test/functional/contracts/SimpleProxy.sol
  test/functional/feature_evm_proxy.py
  test/functional/test_runner.py
Labels: v/next-release

#2409 Refine ain contracts build script and sol artifacts
  lib/ain-contracts/build.rs
  lib/ain-contracts/dfi_reserved/DFIReserved.sol
  lib/ain-contracts/dst20/DST20.sol
  lib/ain-contracts/src/lib.rs
  test/functional/feature_dst20.py
  test/functional/feature_evm_dfi_intrinsics.py
  test/functional/test_framework/util.py
Labels: v/next-release

#2447 EVM: Shift transferdomain transparent tx into the correct attribute
  src/masternodes/consensus/xvm.cpp
  src/masternodes/errors.h
  src/masternodes/rpc_accounts.cpp
  src/miner.cpp
  src/txmempool.cpp
  test/functional/feature_evm_transferdomain.py
Labels: v/next-release
