Repository DeFiCh/ain, pull requests merged in 2023-01, with the labels that each got.

#1613 Change ordering of TXs by time
  src/init.cpp
  src/miner.cpp
  src/miner.h
  src/policy/fees.cpp
  src/rpc/mining.cpp
  src/validation.h
  test/functional/feature_loan_vault.py
  test/lint/lint-circular-dependencies.sh
Labels: kind/chore

#1649 Prevent consortium being set on loan token or DFI
  src/masternodes/mn_rpc.cpp
  test/functional/feature_consortium.py
  test/functional/feature_setgov.py
Labels: kind/fix

#1635 Add pagination support for `listgovproposalvotes`
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/feature, v/3.2.1

#1659 Fix accounting of burntoken tx in getburninfo
  src/masternodes/rpc_accounts.cpp
  src/masternodes/rpc_tokens.cpp
  test/functional/feature_consortium.py
Labels: kind/fix, area/tokens, v/3.2.1

#1627 Add cycle filtering and pagination to listgovproposals
  src/masternodes/proposals.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_proposals.cpp
  src/rpc/client.cpp
  test/functional/feature_on_chain_government.py
  test/functional/rpc_listgovproposals.py
  test/functional/test_runner.py
Labels: kind/feature, v/3.2.1

#1679 Refactor consensus with contract based predicates
  src/amount.h
  src/chainparams.cpp
  src/masternodes/accounts.cpp
  src/masternodes/balances.h
  src/masternodes/govvariables/attributes.cpp
  src/masternodes/govvariables/icx_takerfee_per_btc.cpp
  src/masternodes/govvariables/loan_daily_reward.cpp
  src/masternodes/govvariables/loan_liquidation_penalty.cpp
  src/masternodes/govvariables/loan_splits.cpp
  src/masternodes/govvariables/lp_daily_dfi_reward.cpp
  src/masternodes/govvariables/lp_splits.cpp
  src/masternodes/govvariables/oracle_block_interval.cpp
  src/masternodes/govvariables/oracle_deviation.cpp
  src/masternodes/gv.cpp
  src/masternodes/icxorder.cpp
  src/masternodes/incentivefunding.cpp
  src/masternodes/loan.cpp
  src/masternodes/masternodes.cpp
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/oracles.cpp
  src/masternodes/poolpairs.cpp
  src/masternodes/res.h
  src/masternodes/rpc_oracles.cpp
  src/masternodes/rpc_poolpair.cpp
  src/masternodes/tokens.cpp
  src/masternodes/tokens.h
  src/masternodes/vault.cpp
  src/rpc/rawtransaction_util.cpp
  src/test/util_tests.cpp
  src/validation.cpp
  test/functional/feature_autoauth.py
  test/functional/feature_loan_scheme.py
  test/functional/feature_loan_vault.py
  test/functional/feature_tokens_multisig.py
Labels: kind/chore

#1671 Refactor fork check
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/poolpairs.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_poolpair.cpp
Labels: kind/chore

#1663 Move validation code to DeFi
  src/Makefile.am
  src/masternodes/validation.cpp
  src/masternodes/validation.h
  src/validation.cpp
  src/validation.h
  test/lint/lint-circular-dependencies.sh
  test/lint/lint-locale-dependence.sh
Labels: kind/chore

#1685 Update getblock help dialogue
  src/rpc/blockchain.cpp
Labels: kind/docs

#1651 Add workflow_dispatch event trigger to full sync CI
  .github/workflows/fullsync-tests.yml
Labels: kind/feature

#1689 Fix start pagination for listgovproposals
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
  test/functional/feature_on_chain_government_govvar_update.py
Labels: kind/fix, area/governance, v/3.2.2

#1331 Feature: Auto Backup Wallet
  src/dummywallet.cpp
  src/wallet/init.cpp
  src/wallet/load.cpp
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  test/functional/wallet_multiwallet.py
Labels: kind/feature, v/3.2.2

#1686 Allow direct fetch and reorgs on mocknet
  src/net_processing.cpp
  src/validation.cpp
Labels: kind/fix, v/3.2.2

#1690 Add lock before wallet backup
  src/wallet/walletdb.cpp
Labels: kind/fix, v/3.2.2

#1669 Adds -leveldebchecksum argument
  src/dbwrapper.cpp
  src/dbwrapper.h
  src/init.cpp
  test/lint/check-doc.py
Labels: kind/fix, v/3.2.2

#1643 Add pagination support for `listaccounthistory`
  src/masternodes/rpc_accounts.cpp
  test/functional/feature_listaccounthistory_multiaccountquery.py
  test/functional/rpc_listaccounthistory.py
  test/functional/test_runner.py
Labels: kind/feature, v/3.2.2

#1691 Add alias "special" for emergency VOC.
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/chore, area/governance, v/3.2.2

#1692 Fix `start` behaviour in `listgovproposals`
  src/masternodes/rpc_proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/fix, v/3.2.2

#1693 Update devnet with latest testnet hard fork height
  src/chainparams.cpp
Labels: kind/fix

#1694 Set devnet seed node
  src/chainparams.cpp
Labels: kind/fix, v/3.2.2

#1687 Refactor proposals related nomenclature
  src/consensus/params.h
  src/masternodes/masternodes.cpp
  src/masternodes/masternodes.h
  src/masternodes/mn_checks.cpp
  src/masternodes/mn_checks.h
  src/masternodes/proposals.cpp
  src/masternodes/proposals.h
  src/masternodes/rpc_customtx.cpp
  src/masternodes/rpc_proposals.cpp
  src/masternodes/validation.cpp
Labels: kind/chore, v/3.2.2

#1695 v3.2.2
  configure.ac
Labels: kind/chore, v/3.2.2

#1696 Add devnet ports to dockerfile EXPOSE
  contrib/dockerfiles/dockerhub/x86_64-pc-linux-gnu.dockerfile
Labels: kind/chore

#1698 Add option to pass custom name to workflow_dispatch run
  .github/workflows/fullsync-tests.yml
Labels: kind/feature

#1699 Document missing fork dates
  src/chainparams.cpp
Labels: kind/chore

#1697 Fix cycleEndHeight for emergency VOC
  src/masternodes/proposals.cpp
  test/functional/feature_on_chain_government.py
Labels: kind/fix, area/governance, v/3.2.2

#1710 Next Network Upgrade
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
Labels: kind/feature

#1706 Add OCG voting scenarios tests
  test/functional/feature_on_chain_government_voting_scenarios.py
  test/functional/test_runner.py
Labels: kind/feature
