Repository DeFiCh/ain, pull requests merged in 2023-10, with the labels that each got.

#2521 Set correct timestamp in queue backend
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/evm.rs
  lib/ain-evm/src/txqueue.rs
  lib/ain-rs-exports/src/evm.rs
  lib/ain-rs-exports/src/lib.rs
  src/masternodes/mn_checks.cpp
  src/miner.cpp
  src/validation.cpp
Labels: v/next-release

#2516 EVM: Fix gas used for system txs in tx receipts
  lib/ain-evm/src/backend.rs
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/executor.rs
  test/functional/feature_evm_logs.py
Labels: v/next-release

#2526 EVM: Clean up construct block validation
  lib/ain-evm/src/backend.rs
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/evm.rs
  lib/ain-evm/src/executor.rs
  lib/ain-evm/src/lib.rs
  lib/ain-rs-exports/src/evm.rs
  lib/ain-rs-exports/src/lib.rs
  src/masternodes/validation.cpp
  src/miner.cpp
Labels: v/next-release

#2562 More fmt and lint checks
  ci/lint/deps.sh
  ci/lint/lint.sh
  ci/lint/main.sh
  make.sh
Labels: v/next-release

#2567 evm: Checked U256 casting
  lib/ain-evm/src/block.rs
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/gas.rs
  lib/ain-evm/src/storage/block_store.rs
  lib/ain-evm/src/storage/db.rs
  lib/ain-grpc/src/rpc/eth.rs
  lib/ain-rs-exports/src/evm.rs
Labels: v/next-release

#2565 Check ATTRIBUTE export keys. Do not import empty set.
  src/chainparams.cpp
  src/dfi/consensus/governance.cpp
  src/dfi/errors.h
  src/dfi/govvariables/attributes.cpp
  src/dfi/govvariables/attributes.h
Labels: v/next-release

#2566 EVM: Block template implementation and validation optimization
  lib/ain-evm/src/backend.rs
  lib/ain-evm/src/blocktemplate.rs
  lib/ain-evm/src/contract.rs
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/evm.rs
  lib/ain-evm/src/executor.rs
  lib/ain-evm/src/lib.rs
  lib/ain-evm/src/receipt.rs
  lib/ain-evm/src/txqueue.rs
  lib/ain-evm/tests/block.rs
  lib/ain-grpc/src/rpc/debug.rs
  lib/ain-rs-exports/src/evm.rs
  lib/ain-rs-exports/src/lib.rs
  src/consensus/tx_verify.cpp
  src/dfi/consensus/governance.cpp
  src/dfi/consensus/loans.cpp
  src/dfi/consensus/tokens.cpp
  src/dfi/consensus/txvisitor.cpp
  src/dfi/consensus/txvisitor.h
  src/dfi/consensus/xvm.cpp
  src/dfi/evm.cpp
  src/dfi/evm.h
  src/dfi/govvariables/attributes.cpp
  src/dfi/govvariables/attributes.h
  src/dfi/icxorder.h
  src/dfi/masternodes.cpp
  src/dfi/mn_checks.cpp
  src/dfi/mn_checks.h
  src/dfi/mn_rpc.cpp
  src/dfi/rpc_loan.cpp
  src/dfi/rpc_masternodes.cpp
  src/dfi/rpc_poolpair.cpp
  src/dfi/rpc_tokens.cpp
  src/dfi/tokens.cpp
  src/dfi/tokens.h
  src/dfi/validation.cpp
  src/dfi/validation.h
  src/miner.cpp
  src/miner.h
  src/test/applytx_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
  test/functional/feature_evm_contract_env_vars.py
  test/functional/feature_evm_miner.py
Labels: v/next-release

#2563 Add block and transaction context
  src/consensus/tx_verify.cpp
  src/dfi/consensus/accounts.cpp
  src/dfi/consensus/governance.cpp
  src/dfi/consensus/icxorders.cpp
  src/dfi/consensus/loans.cpp
  src/dfi/consensus/masternodes.cpp
  src/dfi/consensus/oracles.cpp
  src/dfi/consensus/poolpairs.cpp
  src/dfi/consensus/proposals.cpp
  src/dfi/consensus/smartcontracts.cpp
  src/dfi/consensus/tokens.cpp
  src/dfi/consensus/txvisitor.cpp
  src/dfi/consensus/txvisitor.h
  src/dfi/consensus/vaults.cpp
  src/dfi/consensus/xvm.cpp
  src/dfi/customtx.cpp
  src/dfi/customtx.h
  src/dfi/errors.h
  src/dfi/govvariables/attributes.cpp
  src/dfi/gv.cpp
  src/dfi/masternodes.cpp
  src/dfi/masternodes.h
  src/dfi/mn_checks.cpp
  src/dfi/mn_checks.h
  src/dfi/mn_rpc.cpp
  src/dfi/rpc_accounts.cpp
  src/dfi/rpc_loan.cpp
  src/dfi/rpc_poolpair.cpp
  src/dfi/rpc_tokens.cpp
  src/dfi/tokens.cpp
  src/dfi/tokens.h
  src/dfi/validation.cpp
  src/miner.cpp
  src/miner.h
  src/test/applytx_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
  src/validation.h
  test/lint/lint-circular-dependencies.sh
Labels: v/next-release-may-be

#2625 EVM: Fix atomicity of apply operations with backend overlay
  lib/ain-evm/src/backend.rs
  lib/ain-evm/src/evm.rs
  lib/ain-evm/src/executor.rs
  lib/ain-rs-exports/src/evm.rs
Labels: v/next-release

#2616 EVM: Fixes to backend state in storage and fix db dump debug RPC
  lib/ain-evm/src/backend.rs
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/storage/block_store.rs
  lib/ain-evm/src/storage/db.rs
  lib/ain-evm/src/storage/mod.rs
  lib/ain-grpc/src/rpc/debug.rs
  test/functional/feature_evm_dst20.py
  test/functional/feature_evm_rollback.py
Labels: v/next-release

#2634 evm: `debug_traceTransaction`
  lib/Cargo.lock
  lib/Cargo.toml
  lib/ain-cpp-imports/src/bridge.rs
  lib/ain-cpp-imports/src/lib.rs
  lib/ain-evm/Cargo.toml
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/eventlistener.rs
  lib/ain-evm/src/lib.rs
  lib/ain-evm/src/opcode.rs
  lib/ain-grpc/src/rpc/debug.rs
  lib/ain-grpc/src/transaction.rs
  src/ffi/ffiexports.cpp
  src/ffi/ffiexports.h
  src/init.cpp
  test/functional/feature_evm.py
  test/functional/feature_evm_mempool.py
  test/functional/feature_evm_rollback.py
  test/functional/feature_evm_rpc.py
  test/functional/feature_evm_rpc_transaction.py
Labels: v/next-release

#2641 EVM: Clean up backend vicinity
  lib/ain-cpp-imports/src/bridge.rs
  lib/ain-cpp-imports/src/lib.rs
  lib/ain-evm/src/backend.rs
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/eventlistener.rs
  lib/ain-evm/src/executor.rs
  lib/ain-grpc/src/rpc/debug.rs
  lib/ain-grpc/src/transaction.rs
  src/ffi/ffiexports.cpp
  src/ffi/ffiexports.h
Labels: ci/sync

#2639 Enable eager concurrency on ECC recovery pre-cache
  src/dfi/threadpool.cpp
  src/dfi/threadpool.h
  src/validation.cpp
Labels: v/next-release-may-be

#2632 EVM: Add caching and concurrency control flags
  lib/ain-cpp-imports/src/bridge.rs
  lib/ain-cpp-imports/src/lib.rs
  lib/ain-evm/src/core.rs
  src/dfi/threadpool.h
  src/ffi/ffiexports.cpp
  src/ffi/ffiexports.h
  src/init.cpp
  src/validation.cpp
Labels: v/next-release

#2620 Fix: `eth_call` error handling
  lib/ain-grpc/src/errors.rs
  lib/ain-grpc/src/rpc/eth.rs
  lib/ain-grpc/src/utils.rs
  test/functional/contracts/Require.sol
  test/functional/feature_evm_rpc.py
  test/functional/test_framework/util.py
Labels: v/next-release

#2645 Add EVM network parameters for fallback controls
  lib/ain-cpp-imports/src/bridge.rs
  lib/ain-cpp-imports/src/lib.rs
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/evm.rs
  lib/ain-evm/src/storage/cache.rs
  lib/ain-evm/src/storage/mod.rs
  lib/ain-evm/src/storage/traits.rs
  lib/ain-grpc/src/rpc/debug.rs
  lib/ain-grpc/src/rpc/eth.rs
  lib/ain-rs-exports/src/evm.rs
  lib/ain-rs-exports/src/lib.rs
  src/dfi/evm.cpp
  src/dfi/evm.h
  src/dfi/govvariables/attributes.cpp
  src/dfi/govvariables/attributes.h
  src/dfi/mn_checks.cpp
  src/ffi/ffiexports.cpp
  src/ffi/ffiexports.h
  src/miner.cpp
  src/validation.cpp
  test/functional/feature_evm.py
  test/lint/lint-circular-dependencies.sh
Labels: v/next-release

#2648 Make ethSyncStatus coherent
  lib/ain-cpp-imports/src/bridge.rs
  lib/ain-cpp-imports/src/lib.rs
  src/ffi/ffiexports.cpp
  src/ffi/ffiexports.h
Labels: v/next-release
