Repository DeFiCh/ain, pull requests merged in 2023-08, with the labels that each got.

#2315 Check for non-DAT and LP tokens in transferdomain
  src/masternodes/errors.h
  src/masternodes/mn_checks.cpp
  test/functional/feature_evm_transferdomain.py
Labels: evm

#2357 EVM: Fix cache error handling
  lib/ain-evm/src/storage/mod.rs
Labels: evm, rc2

#2383 Fix block creation validation pipeline
  lib/ain-evm/src/core.rs
  lib/ain-evm/src/evm.rs
  lib/ain-evm/src/txqueue.rs
  test/functional/rpc_blockchain.py
Labels: v/next-release

#2391 EVM: Add miner tests
  test/functional/feature_evm.py
  test/functional/feature_evm_miner.py
  test/functional/test_runner.py
Labels: v/next-release

#2372 Fix vmmap RPC auto resolve for block number
  src/masternodes/rpc_evm.cpp
  test/functional/feature_evm_vmmap_rpc.py
Labels: v/next-release
