Repository DeFiCh/ain, pull requests merged in 2024-09, with the labels that each got.

#2975 Add startup flag to set miner strategy
  src/dfi/masternodes.cpp
  src/dfi/masternodes.h
  src/dfi/rpc_masternodes.cpp
  src/init.cpp
  src/logging.cpp
  src/miner.cpp
  src/miner.h
  src/pos.cpp
  src/pos_kernel.cpp
  src/pos_kernel.h
  src/rpc/mining.cpp
  src/test/blockencodings_tests.cpp
  src/test/pos_tests.cpp
  test/functional/feature_masternode_operator.py
  test/functional/rpc_updatemasternode.py
  test/lint/lint-includes.sh
  test/lint/lint-locale-dependence.sh
Labels: e4

#2991 Restructure of Foundation and Governance
  src/dfi/consensus/governance.cpp
  src/dfi/consensus/loans.cpp
  src/dfi/consensus/oracles.cpp
  src/dfi/consensus/poolpairs.cpp
  src/dfi/consensus/tokens.cpp
  src/dfi/consensus/tokens.h
  src/dfi/consensus/txvisitor.cpp
  src/dfi/consensus/txvisitor.h
  src/dfi/govvariables/attributes.cpp
  src/dfi/govvariables/attributes.h
  src/dfi/masternodes.cpp
  src/dfi/masternodes.h
  src/dfi/mn_checks.cpp
  src/dfi/mn_checks.h
  src/dfi/mn_rpc.cpp
  src/dfi/mn_rpc.h
  src/dfi/rpc_customtx.cpp
  src/dfi/rpc_loan.cpp
  src/dfi/rpc_oracles.cpp
  src/dfi/rpc_poolpair.cpp
  src/dfi/rpc_tokens.cpp
  src/dfi/tokens.cpp
  src/dfi/tokens.h
  src/dfi/validation.cpp
  src/txmempool.cpp
  src/validation.cpp
  test/functional/feature_community_governance.py
  test/functional/feature_token_transfer.py
  test/functional/feature_tokens_dat.py
  test/functional/test_runner.py
Labels: protocol, ci/sync, p2, e4

#2976 Implementing the dToken restart
  src/Makefile.am
  src/amount.h
  src/chainparams.cpp
  src/chainparams.h
  src/dfi/accounts.cpp
  src/dfi/accounts.h
  src/dfi/consensus/tokenlock.cpp
  src/dfi/consensus/tokenlock.h
  src/dfi/consensus/xvm.cpp
  src/dfi/customtx.cpp
  src/dfi/customtx.h
  src/dfi/errors.h
  src/dfi/govvariables/attributes.cpp
  src/dfi/govvariables/attributes.h
  src/dfi/masternodes.cpp
  src/dfi/masternodes.h
  src/dfi/mn_checks.cpp
  src/dfi/mn_checks.h
  src/dfi/poolpairs.cpp
  src/dfi/poolpairs.h
  src/dfi/rpc_accounts.cpp
  src/dfi/rpc_customtx.cpp
  src/dfi/validation.cpp
  src/dfi/validation.h
  src/miner.cpp
  test/functional/feature_restart_interest.py
  test/functional/feature_restartdtokens.py
  test/functional/test_framework/test_framework.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
Labels: protocol, e4, dfip

#3039 fix: revert wrong refactor of GetLoanTokensForFutures
  src/dfi/validation.cpp
Labels: ci/sync

#3062 feat: unfreeze mn
  src/dfi/consensus/masternodes.cpp
  src/dfi/errors.h
  src/dfi/govvariables/attributes.cpp
  src/dfi/govvariables/attributes.h
  src/dfi/masternodes.cpp
  src/dfi/masternodes.h
  src/dfi/rpc_masternodes.cpp
  src/dfi/validation.cpp
  src/miner.cpp
  src/pos.cpp
  src/rpc/mining.cpp
  test/functional/feature_unfreeze_masternodes.py
  test/functional/test_runner.py
Labels: protocol, e2

#3072 Remove unfreeze feature
  src/dfi/consensus/masternodes.cpp
  src/dfi/errors.h
  src/dfi/govvariables/attributes.cpp
  src/dfi/govvariables/attributes.h
  src/dfi/masternodes.cpp
  src/dfi/masternodes.h
  src/dfi/rpc_masternodes.cpp
  src/dfi/validation.cpp
  src/miner.cpp
  src/pos.cpp
  src/rpc/mining.cpp
  test/functional/feature_unfreeze_masternodes.py
  test/functional/test_runner.py
Labels: protocol, v/next-network-upgrade, e2
